#if BAE_CLOUDKIT

    import CloudKit
    import Foundation
    import os.log

    private let logger = Logger.bae("CloudKitService")

    /// Implements the CloudKitDriver protocol (generated by UniFFI from Rust).
    /// Each method blocks the calling thread using a DispatchSemaphore while
    /// CloudKit async operations complete.
    final class CloudKitService: CloudKitDriver, @unchecked Sendable {
        private static let containerIdentifier = "iCloud.fm.bae.desktop"
        private static let zoneName = "bae-library"

        private let container = CKContainer(
            identifier: CloudKitService.containerIdentifier
        )
        private let recordType = "BaeFile"

        private var database: CKDatabase {
            container.privateCloudDatabase
        }

        private let zoneID = CKRecordZone.ID(zoneName: CloudKitService.zoneName)

        /// The service pointed at bae's CloudKit container and library zone.
        static func bae() -> CloudKitService {
            CloudKitService()
        }

        /// Pre-flight check the sync setup wizard runs before persisting CloudKit
        /// as the provider. Throws if iCloud isn't available — most often "the
        /// user has iCloud signed out on this device", which the system-level
        /// `accountStatus()` API is exactly designed to report. Without this
        /// check, `useCloudkit()` happily writes `provider: CloudKit` to YAML and
        /// the user discovers via the reconnect banner after the first failed
        /// sync cycle.
        func checkAccountAvailable() async throws {
            let status: CKAccountStatus
            do {
                status = try await container.accountStatus()
            }
            catch {
                throw CloudKitError.Storage(
                    msg:
                        "Couldn't check iCloud account status: \(error.localizedDescription)"
                )
            }
            let unavailableReason: String
            switch status {
            case .available:
                return
            case .noAccount:
                unavailableReason =
                    "No iCloud account is signed in on this device. Open System Settings → Apple ID to sign in, then try again."
            case .restricted:
                unavailableReason =
                    "iCloud is restricted on this device (parental controls or MDM). bae can't use it for sync."
            case .couldNotDetermine:
                unavailableReason =
                    "Couldn't determine iCloud account status. Check your network and try again."
            case .temporarilyUnavailable:
                unavailableReason =
                    "iCloud is temporarily unavailable. Try again in a moment."
            @unknown default:
                unavailableReason =
                    "Unexpected iCloud account status (\(status.rawValue))."
            }
            throw CloudKitError.Storage(msg: unavailableReason)
        }

        // MARK: - Zone Management

        private var zoneEnsured = false

        private func ensureZone() throws {
            guard !zoneEnsured else {
                return
            }
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?
            let zone = CKRecordZone(zoneID: zoneID)
            database.save(zone) { _, error in
                resultError = error
                sem.signal()
            }
            sem.wait()
            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Zone setup")
                )
            }
            zoneEnsured = true
        }

        // MARK: - Record ID from key

        private func recordID(for key: String) -> CKRecord.ID {
            CKRecord.ID(recordName: key, zoneID: zoneID)
        }

        // MARK: - Error classification

        /// Translate a CloudKit operation failure into a user-facing message that
        /// names the account/storage condition and the recovery step. The common
        /// `CKError` codes get specific copy; everything else falls back to the
        /// operation label + `localizedDescription` so transient or unclassified
        /// failures stay debuggable in logs.
        private func cloudKitErrorMessage(_ error: Error, op: String) -> String
        {
            guard let ckError = error as? CKError else {
                return "\(op) failed: \(error.localizedDescription)"
            }
            switch ckError.code {
            case .notAuthenticated:
                return
                    "You're not signed into iCloud. Open System Settings → Apple ID to sign in, then try again."
            case .quotaExceeded:
                return
                    "Your iCloud storage is full. Free up space in System Settings → Apple ID → iCloud to keep syncing."
            case .permissionFailure:
                return
                    "bae doesn't have permission to use iCloud. Open System Settings → Apple ID → iCloud → Apps Using iCloud and turn bae on."
            case .zoneNotFound, .userDeletedZone:
                return
                    "The iCloud sync zone is gone. Reconnect in sync settings to recreate it."
            default:
                return "\(op) failed: \(ckError.localizedDescription)"
            }
        }

        // MARK: - CloudKitDriver Protocol

        func writeRecord(key: String, data: Data) throws {
            try ensureZone()
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?

            let tempURL = FileManager.default.temporaryDirectory
                .appendingPathComponent(UUID().uuidString)
            try data.write(to: tempURL)
            defer {
                do {
                    try FileManager.default.removeItem(at: tempURL)
                }
                catch {
                    logger.warning(
                        "failed to remove temp file \(tempURL.path, privacy: .public): \(error.localizedDescription, privacy: .public)"
                    )
                }
            }

            let record = CKRecord(
                recordType: recordType,
                recordID: recordID(for: key)
            )
            record["key"] = key as CKRecordValue
            record["data"] = CKAsset(fileURL: tempURL)

            let op = CKModifyRecordsOperation(
                recordsToSave: [record],
                recordIDsToDelete: nil
            )
            op.savePolicy = .allKeys
            op.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            database.add(op)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Write")
                )
            }
        }

        func readRecord(key: String) throws -> Data {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultData: Data?
            nonisolated(unsafe) var resultError: Error?

            database.fetch(withRecordID: recordID(for: key)) { record, error in
                if let error {
                    resultError = error
                }
                else if let record, let asset = record["data"] as? CKAsset,
                    let url = asset.fileURL
                {
                    do {
                        resultData = try Data(contentsOf: url)
                    }
                    catch {
                        resultError = error
                    }
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                if let ckError = error as? CKError, ckError.code == .unknownItem
                {
                    throw CloudKitError.NotFound(msg: key)
                }
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Read")
                )
            }
            guard let data = resultData else {
                throw CloudKitError.NotFound(msg: key)
            }
            return data
        }

        func listRecords(prefix: String) throws -> [String] {
            try ensureZone()
            nonisolated(unsafe) var keys: [String] = []

            let predicate = NSPredicate(format: "key BEGINSWITH %@", prefix)
            let query = CKQuery(recordType: recordType, predicate: predicate)

            // Initial fetch
            nonisolated(unsafe) var cursor: CKQueryOperation.Cursor? = nil
            do {
                let sem = DispatchSemaphore(value: 0)
                nonisolated(unsafe) var resultError: Error?
                nonisolated(unsafe) var nextCursor: CKQueryOperation.Cursor?

                database.fetch(withQuery: query, inZoneWith: zoneID) { result in
                    switch result {
                    case .success((let matchResults, let queryCursor)):
                        nextCursor = queryCursor
                        for (_, recordResult) in matchResults {
                            if case .success(let record) = recordResult,
                                let key = record["key"] as? String
                            {
                                keys.append(key)
                            }
                        }
                    case .failure(let error):
                        resultError = error
                    }
                    sem.signal()
                }
                sem.wait()

                if let error = resultError {
                    throw CloudKitError.Storage(
                        msg: cloudKitErrorMessage(error, op: "List")
                    )
                }
                cursor = nextCursor
            }

            // Fetch remaining pages
            while let activeCursor = cursor {
                let sem = DispatchSemaphore(value: 0)
                nonisolated(unsafe) var resultError: Error?
                nonisolated(unsafe) var nextCursor: CKQueryOperation.Cursor?

                database.fetch(withCursor: activeCursor) { result in
                    switch result {
                    case .success((let matchResults, let queryCursor)):
                        nextCursor = queryCursor
                        for (_, recordResult) in matchResults {
                            if case .success(let record) = recordResult,
                                let key = record["key"] as? String
                            {
                                keys.append(key)
                            }
                        }
                    case .failure(let error):
                        resultError = error
                    }
                    sem.signal()
                }
                sem.wait()

                if let error = resultError {
                    throw CloudKitError.Storage(
                        msg: cloudKitErrorMessage(error, op: "List")
                    )
                }
                cursor = nextCursor
            }

            return keys
        }

        func deleteRecord(key: String) throws {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?

            let op = CKModifyRecordsOperation(
                recordsToSave: nil,
                recordIDsToDelete: [recordID(for: key)],
            )
            op.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result {
                    if let ckError = error as? CKError,
                        ckError.code == .unknownItem
                    {
                        // Idempotent delete
                    }
                    else {
                        resultError = error
                    }
                }
                sem.signal()
            }
            database.add(op)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Delete")
                )
            }
        }

        func recordExists(key: String) throws -> Bool {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var exists = false
            nonisolated(unsafe) var resultError: Error?

            database.fetch(withRecordID: recordID(for: key)) { record, error in
                if let error {
                    if let ckError = error as? CKError,
                        ckError.code == .unknownItem
                    {
                        exists = false
                    }
                    else {
                        resultError = error
                    }
                }
                else {
                    exists = record != nil
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Exists check")
                )
            }
            return exists
        }
    }

#endif
