#if BAE_CLOUDKIT

    import CloudKit
    import Foundation
    import os.log

    private let logger = Logger.bae("CloudKitService")

    /// Implements the CloudKitDriver protocol (generated by UniFFI from Rust).
    /// Each method blocks the calling thread using a DispatchSemaphore while
    /// CloudKit async operations complete.
    final class CloudKitService: CloudKitDriver, @unchecked Sendable {
        private static let containerIdentifier = "iCloud.fm.bae.desktop"
        private static let zoneName = "bae-library"

        private let container = CKContainer(
            identifier: CloudKitService.containerIdentifier
        )
        private let recordType = "BaeFile"

        private var privateDatabase: CKDatabase {
            container.privateCloudDatabase
        }

        private var sharedDatabase: CKDatabase {
            container.sharedCloudDatabase
        }

        private let privateZoneID = CKRecordZone.ID(
            zoneName: CloudKitService.zoneName
        )

        /// The service pointed at bae's CloudKit container and library zone.
        static func bae() -> CloudKitService {
            CloudKitService()
        }

        /// Pre-flight check the sync setup wizard runs before persisting CloudKit
        /// as the provider. Throws if iCloud isn't available — most often "the
        /// user has iCloud signed out on this device", which the system-level
        /// `accountStatus()` API is exactly designed to report. Without this
        /// check, `useCloudkit()` happily writes `provider: CloudKit` to YAML and
        /// the user discovers via the reconnect banner after the first failed
        /// sync cycle.
        func checkAccountAvailable() async throws {
            let status: CKAccountStatus
            do {
                status = try await container.accountStatus()
            }
            catch {
                throw CloudKitError.Storage(
                    msg:
                        "Couldn't check iCloud account status: \(error.localizedDescription)"
                )
            }
            let unavailableReason: String
            switch status {
            case .available:
                return
            case .noAccount:
                unavailableReason =
                    "No iCloud account is signed in on this device. Open System Settings → Apple ID to sign in, then try again."
            case .restricted:
                unavailableReason =
                    "iCloud is restricted on this device (parental controls or MDM). bae can't use it for sync."
            case .couldNotDetermine:
                unavailableReason =
                    "Couldn't determine iCloud account status. Check your network and try again."
            case .temporarilyUnavailable:
                unavailableReason =
                    "iCloud is temporarily unavailable. Try again in a moment."
            @unknown default:
                unavailableReason =
                    "Unexpected iCloud account status (\(status.rawValue))."
            }
            throw CloudKitError.Storage(msg: unavailableReason)
        }

        // MARK: - Zone Management

        private var zoneEnsured = false

        private func ensureZone() throws {
            guard !zoneEnsured else {
                return
            }
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?
            let zone = CKRecordZone(zoneID: privateZoneID)
            privateDatabase.save(zone) { _, error in
                resultError = error
                sem.signal()
            }
            sem.wait()
            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Zone setup")
                )
            }
            zoneEnsured = true
        }

        // MARK: - Record ID from key

        private struct RecordScope {
            let database: CKDatabase
            let zoneID: CKRecordZone.ID
            let ownsZone: Bool
        }

        private func recordScope(ownerName: String?, zoneName: String?) throws
            -> RecordScope
        {
            switch (ownerName, zoneName) {
            case (nil, nil):
                return RecordScope(
                    database: privateDatabase,
                    zoneID: privateZoneID,
                    ownsZone: true
                )
            case (.some(let ownerName), .some(let zoneName)):
                guard !ownerName.isEmpty, !zoneName.isEmpty else {
                    throw CloudKitError.Storage(
                        msg:
                            "CloudKit shared scope requires non-empty owner and zone names"
                    )
                }
                return RecordScope(
                    database: sharedDatabase,
                    zoneID: CKRecordZone.ID(
                        zoneName: zoneName,
                        ownerName: ownerName
                    ),
                    ownsZone: false
                )
            case (nil, .some(_)), (.some(_), nil):
                throw CloudKitError.Storage(
                    msg:
                        "CloudKit shared scope requires both owner and zone names"
                )
            }
        }

        private func recordID(for key: String, in scope: RecordScope)
            -> CKRecord.ID
        {
            CKRecord.ID(recordName: key, zoneID: scope.zoneID)
        }

        private func ensureWritableZone(for scope: RecordScope) throws {
            if scope.ownsZone {
                try ensureZone()
            }
        }

        // MARK: - Error classification

        /// Translate a CloudKit operation failure into a user-facing message that
        /// names the account/storage condition and the recovery step. The common
        /// `CKError` codes get specific copy; everything else falls back to the
        /// operation label + `localizedDescription` so transient or unclassified
        /// failures stay debuggable in logs.
        private func cloudKitErrorMessage(_ error: Error, op: String) -> String
        {
            guard let ckError = error as? CKError else {
                return "\(op) failed: \(error.localizedDescription)"
            }
            switch ckError.code {
            case .notAuthenticated:
                return
                    "You're not signed into iCloud. Open System Settings → Apple ID to sign in, then try again."
            case .quotaExceeded:
                return
                    "Your iCloud storage is full. Free up space in System Settings → Apple ID → iCloud to keep syncing."
            case .permissionFailure:
                return
                    "bae doesn't have permission to use iCloud. Open System Settings → Apple ID → iCloud → Apps Using iCloud and turn bae on."
            case .zoneNotFound, .userDeletedZone:
                return
                    "The iCloud sync zone is gone. Reconnect in sync settings to recreate it."
            default:
                return "\(op) failed: \(ckError.localizedDescription)"
            }
        }

    }

    // MARK: - CloudKitDriver Protocol

    extension CloudKitService {
        func writeRecord(
            ownerName: String?,
            zoneName: String?,
            key: String,
            data: Data
        ) throws {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            try ensureWritableZone(for: scope)
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?

            let tempURL = FileManager.default.temporaryDirectory
                .appendingPathComponent(UUID().uuidString)
            try data.write(to: tempURL)
            defer {
                do {
                    try FileManager.default.removeItem(at: tempURL)
                }
                catch {
                    logger.warning(
                        "failed to remove temp file \(tempURL.path): \(error.localizedDescription)"
                    )
                }
            }

            let record = CKRecord(
                recordType: recordType,
                recordID: recordID(for: key, in: scope)
            )
            record["key"] = key as CKRecordValue
            record["data"] = CKAsset(fileURL: tempURL)

            let op = CKModifyRecordsOperation(
                recordsToSave: [record],
                recordIDsToDelete: nil
            )
            op.savePolicy = .allKeys
            op.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            scope.database.add(op)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Write")
                )
            }
        }

        func readRecord(
            ownerName: String?,
            zoneName: String?,
            key: String
        ) throws -> Data {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultData: Data?
            nonisolated(unsafe) var resultError: Error?

            scope.database.fetch(withRecordID: recordID(for: key, in: scope)) {
                record,
                error in
                if let error {
                    resultError = error
                }
                else if let record, let asset = record["data"] as? CKAsset,
                    let url = asset.fileURL
                {
                    do {
                        resultData = try Data(contentsOf: url)
                    }
                    catch {
                        resultError = error
                    }
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                if let ckError = error as? CKError, ckError.code == .unknownItem
                {
                    throw CloudKitError.NotFound(msg: key)
                }
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Read")
                )
            }
            guard let data = resultData else {
                throw CloudKitError.NotFound(msg: key)
            }
            return data
        }

        func listRecords(
            ownerName: String?,
            zoneName: String?,
            prefix: String
        ) throws -> [String] {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            try ensureWritableZone(for: scope)
            var keys: [String] = []

            let predicate = NSPredicate(format: "key BEGINSWITH %@", prefix)
            let query = CKQuery(recordType: recordType, predicate: predicate)

            var cursor = try fetchKeysPage(into: &keys) { handler in
                scope.database.fetch(
                    withQuery: query,
                    inZoneWith: scope.zoneID,
                    completionHandler: handler
                )
            }
            while let activeCursor = cursor {
                cursor = try fetchKeysPage(into: &keys) { handler in
                    scope.database.fetch(
                        withCursor: activeCursor,
                        completionHandler: handler
                    )
                }
            }

            return keys
        }

        /// Run one CloudKit query page synchronously: `issue` starts the fetch
        /// with the given completion handler (the initial `withQuery` or a
        /// follow-up `withCursor`). Appends every matched record's `key` to
        /// `keys` and returns the next page's cursor (`nil` when the last page is
        /// reached). Throws on the page's failure result.
        private func fetchKeysPage(
            into keys: inout [String],
            issue: (
                @escaping (
                    Result<
                        (
                            matchResults: [(
                                CKRecord.ID, Result<CKRecord, Error>
                            )],
                            queryCursor: CKQueryOperation.Cursor?
                        ),
                        Error
                    >
                ) -> Void
            ) -> Void
        ) throws -> CKQueryOperation.Cursor? {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var pageKeys: [String] = []
            nonisolated(unsafe) var resultError: Error?
            nonisolated(unsafe) var nextCursor: CKQueryOperation.Cursor?

            issue { result in
                switch result {
                case .success((let matchResults, let queryCursor)):
                    nextCursor = queryCursor
                    for (_, recordResult) in matchResults {
                        if case .success(let record) = recordResult,
                            let key = record["key"] as? String
                        {
                            pageKeys.append(key)
                        }
                    }
                case .failure(let error):
                    resultError = error
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "List")
                )
            }
            keys.append(contentsOf: pageKeys)
            return nextCursor
        }

        func deleteRecord(
            ownerName: String?,
            zoneName: String?,
            key: String
        ) throws {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?

            let op = CKModifyRecordsOperation(
                recordsToSave: nil,
                recordIDsToDelete: [recordID(for: key, in: scope)],
            )
            op.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result {
                    if let ckError = error as? CKError,
                        ckError.code == .unknownItem
                    {
                        // Idempotent delete
                    }
                    else {
                        resultError = error
                    }
                }
                sem.signal()
            }
            scope.database.add(op)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Delete")
                )
            }
        }

        func recordExists(
            ownerName: String?,
            zoneName: String?,
            key: String
        ) throws -> Bool {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var exists = false
            nonisolated(unsafe) var resultError: Error?

            scope.database.fetch(withRecordID: recordID(for: key, in: scope)) {
                record,
                error in
                if let error {
                    if let ckError = error as? CKError,
                        ckError.code == .unknownItem
                    {
                        exists = false
                    }
                    else {
                        resultError = error
                    }
                }
                else {
                    exists = record != nil
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Exists check")
                )
            }
            return exists
        }

        func grantShare(memberPubkey: String, email: String) throws
            -> BridgeCloudKitShare
        {
            try ensureZoneSupportsSharing()
            let participant = try fetchParticipant(email: email)
            let share =
                try fetchZoneWideShare()
                ?? CKShare(
                    recordZoneID: privateZoneID
                )

            participant.permission = .readWrite
            share.addParticipant(participant)
            share[memberEmailFieldKey(for: memberPubkey)] =
                email as CKRecordValue

            let savedShare = try saveShare(share, op: "Grant share")
            guard let shareURL = savedShare.url?.absoluteString else {
                throw CloudKitError.Storage(
                    msg: "CloudKit did not return a URL for the saved share"
                )
            }
            return BridgeCloudKitShare(
                shareUrl: shareURL,
                ownerName: savedShare.recordID.zoneID.ownerName,
                zoneName: savedShare.recordID.zoneID.zoneName
            )
        }

        func revokeShare(memberPubkey: String, email: String) throws {
            guard let share = try fetchZoneWideShare() else {
                return
            }

            let emailFieldKey = memberEmailFieldKey(for: memberPubkey)
            let mappedEmail = share[emailFieldKey] as? String
            let emailToRemove: String
            if let mappedEmail {
                guard mappedEmail == email else {
                    throw CloudKitError.Storage(
                        msg:
                            "CloudKit share member email does not match signed membership email"
                    )
                }
                emailToRemove = mappedEmail
            }
            else {
                emailToRemove = email
            }

            if let participant = share.participants.first(where: {
                participantMatches($0, email: emailToRemove)
            }) {
                share.removeParticipant(participant)
            }
            else {
                return
            }
            share[emailFieldKey] = nil
            _ = try saveShare(share, op: "Revoke share")
        }

        func acceptShare(shareUrl: String) throws -> BridgeCloudKitShare {
            guard let url = URL(string: shareUrl) else {
                throw CloudKitError.Storage(
                    msg: "CloudKit share URL is invalid"
                )
            }
            let metadata = try fetchShareMetadata(url: url)
            let acceptedShare = try acceptShare(metadata: metadata)
            return BridgeCloudKitShare(
                shareUrl: shareUrl,
                ownerName: acceptedShare.recordID.zoneID.ownerName,
                zoneName: acceptedShare.recordID.zoneID.zoneName
            )
        }

        private func ensureZoneSupportsSharing() throws {
            try ensureZone()
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var fetchedZone: CKRecordZone?
            nonisolated(unsafe) var resultError: Error?

            privateDatabase.fetch(withRecordZoneID: privateZoneID) {
                zone,
                error in
                if let error {
                    resultError = error
                }
                else {
                    fetchedZone = zone
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Share zone lookup")
                )
            }
            guard let fetchedZone else {
                throw CloudKitError.Storage(
                    msg: "CloudKit sharing zone was not returned"
                )
            }
            guard fetchedZone.capabilities.contains(.zoneWideSharing) else {
                throw CloudKitError.Storage(
                    msg: "CloudKit zone-wide sharing is not available"
                )
            }
        }

        private func fetchParticipant(email: String) throws
            -> CKShare.Participant
        {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var participant: CKShare.Participant?
            nonisolated(unsafe) var resultError: Error?

            container.fetchShareParticipant(withEmailAddress: email) {
                fetchedParticipant,
                error in
                if let error {
                    resultError = error
                }
                else {
                    participant = fetchedParticipant
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(
                        error,
                        op: "Share participant lookup"
                    )
                )
            }
            guard let participant else {
                throw CloudKitError.Storage(
                    msg: "CloudKit did not return a share participant"
                )
            }
            return participant
        }

        private func fetchZoneWideShare() throws -> CKShare? {
            let shareID = CKRecord.ID(
                recordName: CKRecordNameZoneWideShare,
                zoneID: privateZoneID
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var share: CKShare?
            nonisolated(unsafe) var resultError: Error?

            privateDatabase.fetch(withRecordID: shareID) { record, error in
                if let error {
                    if let ckError = error as? CKError,
                        ckError.code == .unknownItem
                    {
                        share = nil
                    }
                    else {
                        resultError = error
                    }
                }
                else if let fetchedShare = record as? CKShare {
                    share = fetchedShare
                }
                else if record != nil {
                    resultError = CloudKitError.Storage(
                        msg:
                            "CloudKit zone-wide share record has an unexpected type"
                    )
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Share lookup")
                )
            }
            return share
        }

        private func saveShare(_ share: CKShare, op: String) throws -> CKShare {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var savedShare: CKShare?
            nonisolated(unsafe) var resultError: Error?

            let operation = CKModifyRecordsOperation(
                recordsToSave: [share],
                recordIDsToDelete: nil
            )
            operation.savePolicy = .allKeys
            operation.perRecordSaveBlock = { _, result in
                switch result {
                case .success(let record):
                    if let share = record as? CKShare {
                        savedShare = share
                    }
                    else {
                        resultError = CloudKitError.Storage(
                            msg: "\(op) returned a non-share record"
                        )
                    }
                case .failure(let error):
                    resultError = error
                }
            }
            operation.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            privateDatabase.add(operation)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: op)
                )
            }
            guard let savedShare else {
                throw CloudKitError.Storage(
                    msg: "\(op) failed: CloudKit did not return a share"
                )
            }
            return savedShare
        }

        private func fetchShareMetadata(url: URL) throws -> CKShare.Metadata {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var metadata: CKShare.Metadata?
            nonisolated(unsafe) var resultError: Error?

            let operation = CKFetchShareMetadataOperation(shareURLs: [url])
            operation.perShareMetadataResultBlock = { _, result in
                switch result {
                case .success(let fetchedMetadata):
                    metadata = fetchedMetadata
                case .failure(let error):
                    resultError = error
                }
            }
            operation.fetchShareMetadataResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            operation.container = container
            operation.qualityOfService = .userInitiated
            operation.start()
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(
                        error,
                        op: "Share metadata lookup"
                    )
                )
            }
            guard let metadata else {
                throw CloudKitError.Storage(
                    msg: "CloudKit did not return share metadata"
                )
            }
            return metadata
        }

        private func acceptShare(metadata: CKShare.Metadata) throws -> CKShare {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var acceptedShare: CKShare?
            nonisolated(unsafe) var resultError: Error?

            let operation = CKAcceptSharesOperation(shareMetadatas: [metadata])
            operation.perShareResultBlock = { _, result in
                switch result {
                case .success(let share):
                    acceptedShare = share
                case .failure(let error):
                    resultError = error
                }
            }
            operation.acceptSharesResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            operation.qualityOfService = .userInitiated
            container.add(operation)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Accept share")
                )
            }
            guard let acceptedShare else {
                throw CloudKitError.Storage(
                    msg: "CloudKit did not return accepted share"
                )
            }
            return acceptedShare
        }

        private func memberEmailFieldKey(for memberPubkey: String) -> String {
            let prefix = memberPubkey.prefix(48)
                .map { character in
                    character.isLetter || character.isNumber ? character : "_"
                }
            return "coven_member_\(String(prefix))"
        }

        private func participantMatches(
            _ participant: CKShare.Participant,
            email: String
        ) -> Bool {
            participant.userIdentity.lookupInfo?.emailAddress == email
        }
    }

#endif
