// swift-tools-version: 6.0
import PackageDescription
import Foundation

let packageDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()

// This manifest reads two pieces of on-disk state that the bridge build scripts
// produce: Features.json (the compilation conditions, below) and which
// BaeBridgeFFI xcframework(s) exist under Frameworks/ (the binary targets,
// below). SwiftPM caches the *evaluated* manifest by its source content, which
// is identical regardless of that on-disk state — so both reads are only
// re-observed on a fresh resolve (a CI checkout, a first build, or after a
// clean). Every automated flow runs its bridge build script before resolving,
// so it observes the current state. A machine that resolved BEFORE first
// building a platform's bridge (or that switches feature set / platform in a
// warm build tree) has a stale cached manifest: clear it with
//   rm -rf ~/Library/Caches/org.swift.swiftpm/manifests
// plus the app's DerivedData. Same remediation for both reads.

// Swift compilation conditions generated by bae-bridge/build-{macos,ios}.sh from
// BAE_BRIDGE_FEATURES (the package analog of each app's Features.xcconfig).
// Absent file => no conditions, matching an S3-only (baeium) bridge — the same
// pre-first-build semantics Config.xcconfig documents for its optional include.
// The apps' own Features.xcconfig still drives the app-side #if guards; this
// file only drives the shared package's #if BAE_OAUTH_PROVIDERS / #if BAE_CLOUDKIT.
let features: [SwiftSetting] = {
    let url = packageDir.appendingPathComponent("Features.json")
    // Absent file => no conditions (an S3-only/baeium bridge, or a pre-first-build
    // checkout). This is the one designed default.
    guard FileManager.default.fileExists(atPath: url.path) else { return [] }
    // Present but unreadable or malformed means the generated file is corrupt:
    // fail the build loudly rather than silently mis-building with the wrong
    // feature set (which would compile the shared target against the wrong
    // #if BAE_* branches).
    do {
        let data = try Data(contentsOf: url)
        let names = try JSONDecoder().decode([String].self, from: data)
        return names.map { .define($0) }
    } catch {
        fatalError(
            "BaeKit/Features.json exists but is unreadable/malformed: \(error)"
        )
    }
}()

// Declare a binary target only when its xcframework actually exists on disk.
// SwiftPM validates every declared binaryTarget's artifact at resolve time,
// regardless of the platform the dependency is conditioned on — so declaring the
// iOS xcframework unconditionally breaks a macOS-only build (which never runs
// build-ios.sh, so the iOS artifact is absent), and vice versa. Check the
// xcframework's Info.plist (not just the directory) so a leftover empty dir
// doesn't read as a real artifact. If neither exists, BaeBridge has no binary
// dependency and resolves fine; compiling the bindings then fails with the same
// missing-module error as a missing-bindings build — the documented failure mode.
func xcframeworkExists(_ name: String) -> Bool {
    let plist = packageDir
        .appendingPathComponent("Frameworks")
        .appendingPathComponent(name)
        .appendingPathComponent("Info.plist")
    return FileManager.default.fileExists(atPath: plist.path)
}

var binaryTargets: [Target] = []
var bridgeDependencies: [Target.Dependency] = []
if xcframeworkExists("BaeBridgeFFI.xcframework") {
    binaryTargets.append(
        .binaryTarget(
            name: "BaeBridgeFFI",
            path: "Frameworks/BaeBridgeFFI.xcframework"
        )
    )
    bridgeDependencies.append(
        .target(name: "BaeBridgeFFI", condition: .when(platforms: [.macOS]))
    )
}
if xcframeworkExists("BaeBridgeFFI-ios.xcframework") {
    binaryTargets.append(
        .binaryTarget(
            name: "BaeBridgeFFIiOS",
            path: "Frameworks/BaeBridgeFFI-ios.xcframework"
        )
    )
    bridgeDependencies.append(
        .target(name: "BaeBridgeFFIiOS", condition: .when(platforms: [.iOS]))
    )
}

let package = Package(
    name: "BaeKit",
    defaultLocalization: "en",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [.library(name: "BaeKit", targets: ["BaeKit", "BaeBridge"])],
    dependencies: [
        .package(
            url: "https://github.com/getsentry/sentry-cocoa",
            exact: "9.18.0"
        )
    ],
    targets: binaryTargets + [
        .target(name: "BaeBridge", dependencies: bridgeDependencies),
        .target(
            name: "BaeKit",
            dependencies: [
                "BaeBridge",
                .product(name: "Sentry", package: "sentry-cocoa"),
            ],
            swiftSettings: features
        ),
    ]
)
