// swift-tools-version: 6.0
import PackageDescription
import Foundation

let packageDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()

// This manifest reads two bridge-build outputs: Features.json (the compilation
// conditions below) and the BaeBridgeFFI xcframeworks under Frameworks/. The
// supported fresh-setup flow builds the bridge before xcodegen and SwiftPM
// resolution, as bae-macos/open.sh, bae-macos/run.sh, screenshot capture, and
// CI do. The macOS schemes also refresh stale generated Swift source before
// compilation, but that is deliberately not a fresh-setup path: a scheme
// pre-action runs after package resolution and therefore cannot introduce a
// binary target that this manifest did not see.
//
// SwiftPM caches the evaluated manifest by source content, so switching feature
// sets or platforms in a warm build tree requires clearing
//   rm -rf ~/Library/Caches/org.swift.swiftpm/manifests
// plus the app's DerivedData before resolving again.

// Swift compilation conditions generated by bae-bridge/build-{macos,ios}.sh from
// BAE_BRIDGE_FEATURES (the package analog of each app's Features.xcconfig).
// Absent file => no conditions, matching an S3-only (baeium) bridge. The apps'
// own Features.xcconfig still drives the app-side #if guards; this file only
// drives the shared package's #if BAE_OAUTH_PROVIDERS / #if BAE_CLOUDKIT.
let features: [SwiftSetting] = {
    let url = packageDir.appendingPathComponent("Features.json")
    // Absent file => no conditions for the S3-only/baeium bridge. Full builds
    // generate this file before SwiftPM resolves the package.
    guard FileManager.default.fileExists(atPath: url.path) else { return [] }
    // Present but unreadable or malformed means the generated file is corrupt:
    // fail the build loudly rather than silently mis-building with the wrong
    // feature set (which would compile the shared target against the wrong
    // #if BAE_* branches).
    do {
        let data = try Data(contentsOf: url)
        let names = try JSONDecoder().decode([String].self, from: data)
        return names.map { .define($0) }
    } catch {
        fatalError(
            "BaeKit/Features.json exists but is unreadable/malformed: \(error)"
        )
    }
}()

// Declare a binary target only when its xcframework actually exists on disk.
// SwiftPM validates every declared binaryTarget's artifact at resolve time,
// regardless of the platform the dependency is conditioned on — so declaring the
// iOS xcframework unconditionally breaks a macOS-only build (which never runs
// build-ios.sh, so the iOS artifact is absent), and vice versa. Check the
// xcframework's Info.plist (not just the directory) so a leftover empty dir
// doesn't read as a real artifact. If neither exists, BaeBridge has no binary
// dependency and resolves fine; compiling the bindings then fails with the same
// missing-module error as a missing-bindings build — the documented failure mode.
func xcframeworkExists(_ name: String) -> Bool {
    let plist = packageDir
        .appendingPathComponent("Frameworks")
        .appendingPathComponent(name)
        .appendingPathComponent("Info.plist")
    return FileManager.default.fileExists(atPath: plist.path)
}

var binaryTargets: [Target] = []
var bridgeDependencies: [Target.Dependency] = []
if xcframeworkExists("BaeBridgeFFI.xcframework") {
    binaryTargets.append(
        .binaryTarget(
            name: "BaeBridgeFFI",
            path: "Frameworks/BaeBridgeFFI.xcframework"
        )
    )
    bridgeDependencies.append(
        .target(name: "BaeBridgeFFI", condition: .when(platforms: [.macOS]))
    )
}
if xcframeworkExists("BaeBridgeFFI-ios.xcframework") {
    binaryTargets.append(
        .binaryTarget(
            name: "BaeBridgeFFIiOS",
            path: "Frameworks/BaeBridgeFFI-ios.xcframework"
        )
    )
    bridgeDependencies.append(
        .target(name: "BaeBridgeFFIiOS", condition: .when(platforms: [.iOS]))
    )
}

let package = Package(
    name: "BaeKit",
    defaultLocalization: "en",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [.library(name: "BaeKit", targets: ["BaeKit", "BaeBridge"])],
    dependencies: [
        .package(
            url: "https://github.com/getsentry/sentry-cocoa",
            exact: "9.18.0"
        )
    ],
    targets: binaryTargets + [
        .target(name: "BaeBridge", dependencies: bridgeDependencies),
        .target(
            name: "BaeKit",
            dependencies: [
                "BaeBridge",
                .product(name: "Sentry", package: "sentry-cocoa"),
            ],
            swiftSettings: features
        ),
    ]
)
