#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-target-macos}"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "Usage: $0 [--release]"
    echo "  Builds bae-bridge for macOS (arm64). Debug by default."
    echo ""
    echo "  BAE_BRIDGE_FEATURES selects the cargo feature set (default:"
    echo "  'oauth-providers,cloudkit,desktop'). The Swift compilation"
    echo "  conditions are derived from the same set so the generated bindings"
    echo "  and the app's #if guards never disagree. For a baeium (S3-only)"
    echo "  build: BAE_BRIDGE_FEATURES=desktop $0"
    exit 0
fi

CARGO_PROFILE="debug"
CARGO_FLAGS=""
if [[ "${1:-}" == "--release" ]]; then
    CARGO_PROFILE="release"
    CARGO_FLAGS="--release"
fi

# The cargo feature set the bridge compiles with. The Swift bindings only
# export the bridge functions whose features are on, so the app's #if guards
# must match exactly. Both the bindings and the guards derive from this one
# variable — there's no second place to keep in sync.
BAE_BRIDGE_FEATURES="${BAE_BRIDGE_FEATURES:-oauth-providers,cloudkit,desktop}"

# Map each Rust feature to its Swift compilation condition. A build compiled
# with `oauth-providers` defines BAE_OAUTH_PROVIDERS; one without it must not.
SWIFT_CONDITIONS=""
case ",$BAE_BRIDGE_FEATURES," in
    *,oauth-providers,*) SWIFT_CONDITIONS="$SWIFT_CONDITIONS BAE_OAUTH_PROVIDERS" ;;
esac
case ",$BAE_BRIDGE_FEATURES," in
    *,cloudkit,*) SWIFT_CONDITIONS="$SWIFT_CONDITIONS BAE_CLOUDKIT" ;;
esac
SWIFT_CONDITIONS="$(echo "$SWIFT_CONDITIONS" | xargs)"

# A build without cloudkit signs with the baeium entitlements, which drop the
# iCloud-container keys (a paid account with the iCloud capability is required to
# sign them) but keep keychain access for the cloud keychain. The full build
# leaves CODE_SIGN_ENTITLEMENTS at the default Signing.xcconfig sets.
ENTITLEMENTS_OVERRIDE=""
case ",$BAE_BRIDGE_FEATURES," in
    *,cloudkit,*) ;;
    *) ENTITLEMENTS_OVERRIDE="CODE_SIGN_ENTITLEMENTS = bae/bae-baeium.entitlements" ;;
esac

# Use sccache if available
if command -v sccache &> /dev/null; then
    export RUSTC_WRAPPER=sccache
fi

echo "Building for macOS (arm64, $CARGO_PROFILE, features: $BAE_BRIDGE_FEATURES)..."
cargo build $CARGO_FLAGS --target aarch64-apple-darwin -p bae-bridge --features "$BAE_BRIDGE_FEATURES"

# Write the Swift compilation conditions derived from the feature set. The
# Xcode project includes this file (via Signing.xcconfig) so the #if guards in
# the app track whatever the bridge was built with. DEBUG is preserved via
# $(inherited) so debug-only Swift keeps compiling.
FEATURES_XCCONFIG="bae-macos/bae/Features.xcconfig"
echo "Writing Swift compilation conditions: ${SWIFT_CONDITIONS:-(none)}"
{
    echo "// Generated by bae-bridge/build-macos.sh from BAE_BRIDGE_FEATURES."
    echo "// Do not edit: it is overwritten on every bridge build and tracks the"
    echo "// cargo feature set the bridge was compiled with."
    echo "SWIFT_ACTIVE_COMPILATION_CONDITIONS = \$(inherited) $SWIFT_CONDITIONS"
    [ -n "$ENTITLEMENTS_OVERRIDE" ] && echo "$ENTITLEMENTS_OVERRIDE"
} > "$FEATURES_XCCONFIG"

echo "Generating Swift bindings..."
SWIFT_BINDINGS_DIR="bae-bridge/swift-bindings-macos"
mkdir -p "$SWIFT_BINDINGS_DIR"
cargo run --bin uniffi-bindgen generate \
    --library "$CARGO_TARGET_DIR/aarch64-apple-darwin/$CARGO_PROFILE/libbae_bridge.a" \
    --language swift \
    --out-dir "$SWIFT_BINDINGS_DIR/"

cp "$SWIFT_BINDINGS_DIR/bae_bridge.swift" bae-macos/bae/bae/bae_bridge.swift

echo "Generating localization String Catalog (Apple)..."
cargo run -q -p bae-loc --bin loc-gen -- emit --target apple --out-dir bae-macos/bae/bae

echo "Creating XCFramework..."
rm -rf bae-macos/BaeBridgeFFI.xcframework

mkdir -p "$SWIFT_BINDINGS_DIR/headers"
cp "$SWIFT_BINDINGS_DIR/bae_bridgeFFI.h" "$SWIFT_BINDINGS_DIR/headers/"
cp "$SWIFT_BINDINGS_DIR/bae_bridgeFFI.modulemap" "$SWIFT_BINDINGS_DIR/headers/module.modulemap"

xcodebuild -create-xcframework \
    -library "$CARGO_TARGET_DIR/aarch64-apple-darwin/$CARGO_PROFILE/libbae_bridge.a" \
    -headers "$SWIFT_BINDINGS_DIR/headers" \
    -output bae-macos/BaeBridgeFFI.xcframework

echo ""
echo "Done ($CARGO_PROFILE). Outputs:"
echo "  bae-macos/BaeBridgeFFI.xcframework/"
echo "  $SWIFT_BINDINGS_DIR/bae_bridge.swift"
