#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

# This script compiles the bridge and then reads the resulting staticlib back
# out of the target dir to generate bindings from it, so it has to own the
# directory it reads from. An inherited CARGO_TARGET_DIR can be shared with
# other checkouts, and a concurrent build there rewrites the same artifact from
# different sources between the build and the read — the generators then emit
# bindings for a bridge nobody asked for, and it surfaces later as a Swift or
# C# compile error nowhere near its cause. Local and unconditional on purpose.
export CARGO_TARGET_DIR="target-macos"
MACOS_TARGET="aarch64-apple-darwin"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "Usage: $0 [--release]"
    echo "  Builds bae-bridge for macOS (arm64). Debug by default."
    echo ""
    echo "  BAE_BRIDGE_FEATURES selects the cargo feature set (default:"
    echo "  'oauth-providers,cloudkit,desktop'). The Swift compilation"
    echo "  conditions are derived from the same set so the generated bindings"
    echo "  and the app's #if guards never disagree. For a baeium (S3-only)"
    echo "  build: BAE_BRIDGE_FEATURES=desktop $0"
    exit 0
fi

CARGO_PROFILE="debug"
CARGO_FLAGS=""
if [[ "${1:-}" == "--release" ]]; then
    CARGO_PROFILE="release"
    CARGO_FLAGS="--release"
fi

# The cargo feature set the bridge compiles with. The Swift bindings only
# export the bridge functions whose features are on, so the app's #if guards
# must match exactly. Both the bindings and the guards derive from this one
# variable — there's no second place to keep in sync.
BAE_BRIDGE_FEATURES="${BAE_BRIDGE_FEATURES:-oauth-providers,cloudkit,desktop}"
export BAE_BRIDGE_FEATURES

# Map each Rust feature to its Swift compilation condition. A build compiled
# with `oauth-providers` defines BAE_OAUTH_PROVIDERS; one without it must not.
SWIFT_CONDITIONS=""
case ",$BAE_BRIDGE_FEATURES," in
    *,oauth-providers,*) SWIFT_CONDITIONS="$SWIFT_CONDITIONS BAE_OAUTH_PROVIDERS" ;;
esac
case ",$BAE_BRIDGE_FEATURES," in
    *,cloudkit,*) SWIFT_CONDITIONS="$SWIFT_CONDITIONS BAE_CLOUDKIT" ;;
esac
SWIFT_CONDITIONS="$(echo "$SWIFT_CONDITIONS" | xargs)"

# A build without cloudkit signs with the baeium entitlements, which drop the
# iCloud-container keys (a paid account with the iCloud capability is required to
# sign them) but keep keychain access for the cloud keychain. The full build
# leaves CODE_SIGN_ENTITLEMENTS at the default Signing.xcconfig sets.
ENTITLEMENTS_OVERRIDE=""
case ",$BAE_BRIDGE_FEATURES," in
    *,cloudkit,*) ;;
    *) ENTITLEMENTS_OVERRIDE="CODE_SIGN_ENTITLEMENTS = bae/bae-baeium.entitlements" ;;
esac

# Use sccache if available, unless the caller already selected a wrapper.
if [ -z "${RUSTC_WRAPPER+x}" ] && command -v sccache &> /dev/null; then
    export RUSTC_WRAPPER=sccache
fi

echo "Building for macOS (arm64, $CARGO_PROFILE, features: $BAE_BRIDGE_FEATURES)..."
cargo build $CARGO_FLAGS --target "$MACOS_TARGET" -p bae-bridge \
    --lib --bin uniffi-bindgen --features "$BAE_BRIDGE_FEATURES"

# Write the Swift compilation conditions derived from the feature set. The
# Xcode project includes this file (via Signing.xcconfig) so the #if guards in
# the app track whatever the bridge was built with. DEBUG is preserved via
# $(inherited) so debug-only Swift keeps compiling.
FEATURES_XCCONFIG="bae-macos/bae/Features.xcconfig"
echo "Writing Swift compilation conditions: ${SWIFT_CONDITIONS:-(none)}"
FEATURES_XCCONFIG_TMP="${FEATURES_XCCONFIG}.tmp.$$"
{
    echo "// Generated by bae-bridge/build-macos.sh from BAE_BRIDGE_FEATURES."
    echo "// Do not edit: it is overwritten on every bridge build and tracks the"
    echo "// cargo feature set the bridge was compiled with."
    echo "SWIFT_ACTIVE_COMPILATION_CONDITIONS = \$(inherited) $SWIFT_CONDITIONS"
    [ -n "$ENTITLEMENTS_OVERRIDE" ] && echo "$ENTITLEMENTS_OVERRIDE"
} > "$FEATURES_XCCONFIG_TMP"
if cmp -s "$FEATURES_XCCONFIG_TMP" "$FEATURES_XCCONFIG"; then
    rm "$FEATURES_XCCONFIG_TMP"
else
    mv "$FEATURES_XCCONFIG_TMP" "$FEATURES_XCCONFIG"
fi

SWIFT_BINDINGS_DIR="bae-bridge/swift-bindings-macos"
STATIC_LIB="$CARGO_TARGET_DIR/$MACOS_TARGET/$CARGO_PROFILE/libbae_bridge.a"
BINDGEN="$CARGO_TARGET_DIR/$MACOS_TARGET/$CARGO_PROFILE/uniffi-bindgen"
INSTALLED_BINDINGS="BaeKit/Sources/BaeBridge/bae_bridge_macos.swift"
XCFRAMEWORK="BaeKit/Frameworks/BaeBridgeFFI.xcframework"
COMPLETION_STAMP="$SWIFT_BINDINGS_DIR/.generation-complete"
EXPECTED_STAMP="$CARGO_PROFILE|$BAE_BRIDGE_FEATURES"
NEEDS_GENERATION=0

if [[ ! -f "$COMPLETION_STAMP" ]]; then
    NEEDS_GENERATION=1
else
    STAMP_CONTENT="$(cat "$COMPLETION_STAMP")"
    if [[ "$STAMP_CONTENT" != "$EXPECTED_STAMP" ]] ||
       [[ "$STATIC_LIB" -nt "$COMPLETION_STAMP" ]] ||
       [[ ! -f "$SWIFT_BINDINGS_DIR/bae_bridge.swift" ]] ||
       [[ ! -f "$SWIFT_BINDINGS_DIR/bae_bridgeFFI.h" ]] ||
       [[ ! -f "$SWIFT_BINDINGS_DIR/bae_bridgeFFI.modulemap" ]] ||
       [[ ! -f "$INSTALLED_BINDINGS" ]] ||
       [[ ! -f "$XCFRAMEWORK/Info.plist" ]]; then
        NEEDS_GENERATION=1
    fi
fi

if [[ "$NEEDS_GENERATION" -eq 1 ]]; then
    echo "Generating Swift bindings and XCFramework..."
    rm -f "$COMPLETION_STAMP"

    GENERATION_TMP="$(mktemp -d "$CARGO_TARGET_DIR/bridge-generation.XXXXXX")"
    trap 'rm -rf "$GENERATION_TMP" "$FEATURES_XCCONFIG_TMP"' EXIT
    GENERATED_BINDINGS="$GENERATION_TMP/swift-bindings"
    GENERATED_XCFRAMEWORK="$GENERATION_TMP/BaeBridgeFFI.xcframework"
    mkdir -p "$GENERATED_BINDINGS"

    "$BINDGEN" generate \
        --library "$STATIC_LIB" \
        --language swift \
        --out-dir "$GENERATED_BINDINGS/"

    mkdir -p "$GENERATED_BINDINGS/headers"
    cp "$GENERATED_BINDINGS/bae_bridgeFFI.h" "$GENERATED_BINDINGS/headers/"
    cp "$GENERATED_BINDINGS/bae_bridgeFFI.modulemap" \
        "$GENERATED_BINDINGS/headers/module.modulemap"

    xcodebuild -create-xcframework \
        -library "$STATIC_LIB" \
        -headers "$GENERATED_BINDINGS/headers" \
        -output "$GENERATED_XCFRAMEWORK"

    rm -rf "$SWIFT_BINDINGS_DIR"
    mv "$GENERATED_BINDINGS" "$SWIFT_BINDINGS_DIR"
    ./bae-bridge/install-swift-bindings.sh macos

    rm -rf "$XCFRAMEWORK"
    # Nothing under BaeKit/Frameworks/ is tracked, so a fresh checkout (a new
    # worktree, CI) has no parent dir for the mv.
    mkdir -p "$(dirname "$XCFRAMEWORK")"
    mv "$GENERATED_XCFRAMEWORK" "$XCFRAMEWORK"

    STAMP_TMP="$SWIFT_BINDINGS_DIR/.generation-complete.tmp.$$"
    printf '%s\n' "$EXPECTED_STAMP" > "$STAMP_TMP"
    mv "$STAMP_TMP" "$COMPLETION_STAMP"

    rm -rf "$GENERATION_TMP"
    trap - EXIT
fi

echo "Generating localization String Catalog (Apple)..."
cargo run -q $CARGO_FLAGS --target "$MACOS_TARGET" -p bae-loc --bin loc-gen -- \
    emit --target apple --out-dir bae-macos/bae/bae

echo ""
echo "Done ($CARGO_PROFILE). Outputs:"
echo "  $XCFRAMEWORK/"
echo "  $INSTALLED_BINDINGS"
