#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

# This script reads the staticlib it builds back out of the target dir, so it
# owns that dir: a shared one can be rewritten by another checkout in between.
export CARGO_TARGET_DIR="target-ios"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "Usage: $0 [--release]"
    echo "  Builds bae-bridge for iOS (device + simulator). Debug by default."
    echo ""
    echo "  BAE_BRIDGE_FEATURES selects the cargo feature set (default:"
    echo "  'oauth-providers,cloudkit,cast'; iOS has no 'desktop'). The Swift"
    echo "  compilation conditions are derived from the same set so the generated"
    echo "  bindings and the app's #if guards never disagree. For a baeium"
    echo "  (S3-only) build: BAE_BRIDGE_FEATURES=cast $0"
    exit 0
fi

CARGO_PROFILE="debug"
CARGO_FLAGS=""
if [[ "${1:-}" == "--release" ]]; then
    CARGO_PROFILE="release"
    CARGO_FLAGS="--release"
fi

# The bridge's cargo features, from which the Swift #if conditions are derived.
# Only an unset variable takes the default; the baeium build is `cast`.
BAE_BRIDGE_FEATURES="${BAE_BRIDGE_FEATURES-oauth-providers,cloudkit,cast}"
export BAE_BRIDGE_FEATURES

# Each Rust feature's Swift compilation condition.
SWIFT_CONDITIONS=""
case ",$BAE_BRIDGE_FEATURES," in
    *,oauth-providers,*) SWIFT_CONDITIONS="$SWIFT_CONDITIONS BAE_OAUTH_PROVIDERS" ;;
esac
case ",$BAE_BRIDGE_FEATURES," in
    *,cloudkit,*) SWIFT_CONDITIONS="$SWIFT_CONDITIONS BAE_CLOUDKIT" ;;
esac
SWIFT_CONDITIONS="$(echo "$SWIFT_CONDITIONS" | xargs)"

# Without cloudkit the app signs with the baeium entitlements, which drop the
# iCloud keys so a free provisioning profile can sign it.
ENTITLEMENTS_OVERRIDE=""
case ",$BAE_BRIDGE_FEATURES," in
    *,cloudkit,*) ;;
    *) ENTITLEMENTS_OVERRIDE="CODE_SIGN_ENTITLEMENTS = bae/bae-baeium.entitlements" ;;
esac

if command -v sccache &> /dev/null; then
    export RUSTC_WRAPPER=sccache
fi

rustup target add aarch64-apple-ios aarch64-apple-ios-sim 2>/dev/null || true

# At least the prebuilt FFmpeg libs' minimum (16.0), or the link needs runtime
# symbols the SDK lacks.
IOS_DEPLOYMENT_TARGET=16.0

# ffmpeg-sys-next finds FFmpeg through FFMPEG_DIR and then does not pass the
# target to bindgen, so these per-arch clang args are what keep its struct
# layouts from being the host's. The static libs come from scripts/build-ffmpeg-ios.sh.
FFMPEG_DEVICE="$(pwd)/bae-ffmpeg/ios/aarch64-apple-ios"
FFMPEG_SIM="$(pwd)/bae-ffmpeg/ios/aarch64-apple-ios-sim"
if [ ! -f "$FFMPEG_DEVICE/lib/libavcodec.a" ]; then
    echo "FFmpeg for iOS not built. Run: ./scripts/build-ffmpeg-ios.sh" >&2
    exit 1
fi

DEVICE_SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
SIM_SDK="$(xcrun --sdk iphonesimulator --show-sdk-path)"
HOST_SDK="$(xcrun --sdk macosx --show-sdk-path)"

# FFmpeg needs zlib, which the cdylib link has to name.
IOS_RUSTFLAGS="${RUSTFLAGS:-} -C link-arg=-lz"

run_host_cargo() {
    env -u IPHONEOS_DEPLOYMENT_TARGET \
        -u RUSTFLAGS \
        -u CARGO_ENCODED_RUSTFLAGS \
        -u BINDGEN_EXTRA_CLANG_ARGS \
        SDKROOT="$HOST_SDK" \
        MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-14.0}" \
        cargo "$@"
}

echo "Building for iOS device (arm64, $CARGO_PROFILE, features: $BAE_BRIDGE_FEATURES)..."
FFMPEG_DIR="$FFMPEG_DEVICE" \
IPHONEOS_DEPLOYMENT_TARGET="$IOS_DEPLOYMENT_TARGET" \
RUSTFLAGS="$IOS_RUSTFLAGS" \
BINDGEN_EXTRA_CLANG_ARGS="--target=arm64-apple-ios16.0 -isysroot $DEVICE_SDK -I$FFMPEG_DEVICE/include" \
cargo build $CARGO_FLAGS --target aarch64-apple-ios -p bae-bridge --features "$BAE_BRIDGE_FEATURES"

echo "Building for iOS simulator (arm64, $CARGO_PROFILE, features: $BAE_BRIDGE_FEATURES)..."
FFMPEG_DIR="$FFMPEG_SIM" \
IPHONEOS_DEPLOYMENT_TARGET="$IOS_DEPLOYMENT_TARGET" \
RUSTFLAGS="$IOS_RUSTFLAGS" \
SDKROOT="$SIM_SDK" \
BINDGEN_EXTRA_CLANG_ARGS="--sysroot=$SIM_SDK -target arm64-apple-ios16.0-simulator -I$FFMPEG_SIM/include" \
cargo build $CARGO_FLAGS --target aarch64-apple-ios-sim -p bae-bridge --features "$BAE_BRIDGE_FEATURES"

# The Swift compilation conditions for the feature set, which project.yml
# includes.
FEATURES_XCCONFIG="bae-ios/bae/Features.xcconfig"
echo "Writing Swift compilation conditions: ${SWIFT_CONDITIONS:-(none)}"
{
    echo "// Generated by bae-bridge/build-ios.sh from BAE_BRIDGE_FEATURES."
    echo "// Do not edit: it is overwritten on every bridge build and tracks the"
    echo "// cargo feature set the bridge was compiled with."
    echo "SWIFT_ACTIVE_COMPILATION_CONDITIONS = \$(inherited) $SWIFT_CONDITIONS"
    [ -n "$ENTITLEMENTS_OVERRIDE" ] && echo "$ENTITLEMENTS_OVERRIDE"
} > "$FEATURES_XCCONFIG"

echo "Generating Swift bindings..."
SWIFT_BINDINGS_DIR="bae-bridge/swift-bindings-ios"
mkdir -p "$SWIFT_BINDINGS_DIR"
# The generator is its own host-only package so this build doesn't compile
# bae-core again.
run_host_cargo build -p bae-uniffi-bindgen
BINDGEN="$CARGO_TARGET_DIR/debug/uniffi-bindgen"
"$BINDGEN" generate \
    --library "$CARGO_TARGET_DIR/aarch64-apple-ios/$CARGO_PROFILE/libbae_bridge.a" \
    --language swift \
    --out-dir "$SWIFT_BINDINGS_DIR/"

echo "Generating localization String Catalog (Apple)..."
run_host_cargo run -q -p bae-loc --bin loc-gen -- emit --target apple --out-dir bae-ios/bae/bae
run_host_cargo run -q -p bae-loc --bin loc-gen -- emit --target apple --out-dir BaeKit/Sources/BaeKit/Resources

echo "Generating the theme (Apple)..."
run_host_cargo run -q -p bae-theme --bin theme-gen -- emit --target apple --out-dir BaeKit/Sources/BaeKit/Generated

# The iOS app compiles against bindings matching the iOS xcframework, installed
# as their own os(iOS)-gated file.
./bae-bridge/install-swift-bindings.sh ios

# A Rust staticlib doesn't carry its C dependencies, so the FFmpeg libs are
# merged in and the app links only the xcframework. libswscale is not linked.
echo "Merging FFmpeg static libs into the bridge lib..."
DEVICE_MERGED="$CARGO_TARGET_DIR/aarch64-apple-ios/$CARGO_PROFILE/libbae_bridge_merged.a"
SIM_MERGED="$CARGO_TARGET_DIR/aarch64-apple-ios-sim/$CARGO_PROFILE/libbae_bridge_merged.a"
libtool -static -o "$DEVICE_MERGED" \
    "$CARGO_TARGET_DIR/aarch64-apple-ios/$CARGO_PROFILE/libbae_bridge.a" \
    "$FFMPEG_DEVICE/lib/libavcodec.a" \
    "$FFMPEG_DEVICE/lib/libavformat.a" \
    "$FFMPEG_DEVICE/lib/libavutil.a" \
    "$FFMPEG_DEVICE/lib/libswresample.a"
libtool -static -o "$SIM_MERGED" \
    "$CARGO_TARGET_DIR/aarch64-apple-ios-sim/$CARGO_PROFILE/libbae_bridge.a" \
    "$FFMPEG_SIM/lib/libavcodec.a" \
    "$FFMPEG_SIM/lib/libavformat.a" \
    "$FFMPEG_SIM/lib/libavutil.a" \
    "$FFMPEG_SIM/lib/libswresample.a"

echo "Creating iOS XCFramework..."
rm -rf BaeKit/Frameworks/BaeBridgeFFI-ios.xcframework

mkdir -p "$SWIFT_BINDINGS_DIR/headers"
cp "$SWIFT_BINDINGS_DIR/bae_bridgeFFI.h" "$SWIFT_BINDINGS_DIR/headers/"
cp "$SWIFT_BINDINGS_DIR/bae_bridgeFFI.modulemap" "$SWIFT_BINDINGS_DIR/headers/module.modulemap"

xcodebuild -create-xcframework \
    -library "$DEVICE_MERGED" \
    -headers "$SWIFT_BINDINGS_DIR/headers" \
    -library "$SIM_MERGED" \
    -headers "$SWIFT_BINDINGS_DIR/headers" \
    -output BaeKit/Frameworks/BaeBridgeFFI-ios.xcframework

echo ""
echo "Done ($CARGO_PROFILE). Outputs:"
echo "  BaeKit/Frameworks/BaeBridgeFFI-ios.xcframework/"
echo "  BaeKit/Sources/BaeBridge/bae_bridge_ios.swift"
