#if BAE_CLOUDKIT

    import BaeKit
    import CloudKit
    import Foundation
    import os.log

    private let logger = Logger.bae("CloudKitService")

    /// Implements the CloudKitDriver protocol (generated by UniFFI from Rust).
    /// Each method blocks the calling thread using a DispatchSemaphore while
    /// CloudKit async operations complete.
    public final class CloudKitService: CloudKitDriver, @unchecked Sendable {
        private static let containerIdentifier = "iCloud.fm.bae.desktop"
        private static let zoneName = "bae-library"

        private let containerLock = NSLock()
        private var retainedContainer: CKContainer?
        private let recordType = "BaeFile"

        private var container: CKContainer {
            containerLock.lock()
            defer { containerLock.unlock() }

            if let retainedContainer {
                return retainedContainer
            }

            let container = CKContainer(
                identifier: CloudKitService.containerIdentifier
            )
            retainedContainer = container
            return container
        }

        /// Set once `ensureZone` has created (or confirmed) the library zone,
        /// so later writes skip the round trip. Stored here rather than beside
        /// `ensureZone` because an extension cannot hold stored properties.
        private var zoneEnsured = false

        /// Which CloudKit deployment this build talks to. A debug build runs
        /// against the development container; a release build against production.
        private static var environment: BridgeCloudKitEnvironment {
            #if DEBUG
                .development
            #else
                .production
            #endif
        }

        /// Records staged for an atomic create, keyed by batch id. Nothing here
        /// has reached CloudKit — the commit sends the whole set at once.
        private var staged: [String: [StagedRecord]] = [:]
        private let stagingLock = NSLock()

        private var privateDatabase: CKDatabase {
            container.privateCloudDatabase
        }

        private var sharedDatabase: CKDatabase {
            container.sharedCloudDatabase
        }

        private let privateZoneID = CKRecordZone.ID(
            zoneName: CloudKitService.zoneName
        )

        /// The service pointed at bae's CloudKit container and library zone.
        public static func bae() -> CloudKitService {
            CloudKitService()
        }

        func accountStatus() async throws -> CKAccountStatus {
            try await container.accountStatus()
        }

        // MARK: - Provider identity and accepted share

        /// The CloudKit facts coven binds a store's principal to: which
        /// container and environment this build talks to, which zone the scope
        /// names, and which user record the signed-in iCloud account is. coven
        /// checks the returned owner/zone against the scope it asked about, so a
        /// mismatch is surfaced rather than silently accepted.
        public func providerIdentity(
            ownerName: String?,
            zoneName: String?
        ) throws -> BridgeCloudKitProviderIdentity {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let userRecordName = try fetchCurrentUserRecordName()
            return BridgeCloudKitProviderIdentity(
                containerId: CloudKitService.containerIdentifier,
                environment: CloudKitService.environment,
                ownerName: resolvedOwnerName(
                    for: scope,
                    userRecordName: userRecordName
                ),
                zoneName: scope.zoneID.zoneName,
                currentUserRecordName: userRecordName
            )
        }

        /// The accepted zone-wide CKShare behind a shared scope, with the exact
        /// bytes CloudKit stores for the share record.
        ///
        /// `canonicalRecord` is `CKShare.encodeSystemFields`, which is CloudKit's
        /// own stable encoding of the record's identity and metadata — the same
        /// bytes on every device that fetches the same share version. coven
        /// hashes them into its cross-principal evidence, so anything derived
        /// locally (a re-serialized struct, a description string) would not do.
        public func acceptedReadWriteShare(
            ownerName: String?,
            zoneName: String?
        ) throws -> BridgeCloudKitAcceptedShare {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            guard !scope.ownsZone else {
                throw CloudKitError.Storage(
                    msg:
                        "CloudKit accepted-share lookup needs a shared scope, not the owner's own zone"
                )
            }
            let share = try fetchAcceptedShare(in: scope)
            let userRecordName = try fetchCurrentUserRecordName()
            guard
                let participant = share.participants.first(where: {
                    $0.userIdentity.userRecordID?.recordName == userRecordName
                })
            else {
                throw CloudKitError.Storage(
                    msg:
                        "this device's iCloud account is not a participant in the CloudKit share"
                )
            }
            let archiver = NSKeyedArchiver(requiringSecureCoding: true)
            share.encodeSystemFields(with: archiver)
            archiver.finishEncoding()
            return BridgeCloudKitAcceptedShare(
                shareRecordName: share.recordID.recordName,
                ownerName: scope.zoneID.ownerName,
                zoneName: scope.zoneID.zoneName,
                participantRecordName: userRecordName,
                permission: participant.permission == .readWrite
                    ? .readWrite : .readOnly,
                acceptance: participant.acceptanceStatus == .accepted
                    ? .accepted : .pending,
                canonicalRecord: archiver.encodedData
            )
        }

        /// The share record for an already-shared zone, or nil when the zone was
        /// never shared. A zone-wide share is one URL-accept share for everyone,
        /// so the member key selects nothing — it is the same share or none.
        public func shareForMember(memberPubkey: String) throws
            -> BridgeCloudKitShare?
        {
            guard let share = try fetchZoneWideShare(),
                let url = share.url?.absoluteString
            else {
                return nil
            }
            return BridgeCloudKitShare(
                shareUrl: url,
                ownerName: share.recordID.zoneID.ownerName,
                zoneName: share.recordID.zoneID.zoneName
            )
        }

        private func resolvedOwnerName(
            for scope: RecordScope,
            userRecordName: String
        ) -> String {
            // A record in one's own private database carries the placeholder
            // owner name; the store's principal is this account's user record.
            scope.zoneID.ownerName == CKCurrentUserDefaultName
                ? userRecordName : scope.zoneID.ownerName
        }

        private func fetchCurrentUserRecordName() throws -> String {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var recordID: CKRecord.ID?
            nonisolated(unsafe) var resultError: Error?
            container.fetchUserRecordID { id, error in
                if let error {
                    resultError = error
                }
                else {
                    recordID = id
                }
                sem.signal()
            }
            sem.wait()
            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "User record lookup")
                )
            }
            guard let recordID else {
                throw CloudKitError.Storage(
                    msg: "CloudKit returned no user record for this account"
                )
            }
            return recordID.recordName
        }

        private func fetchAcceptedShare(in scope: RecordScope) throws -> CKShare
        {
            let shareID = CKRecord.ID(
                recordName: CKRecordNameZoneWideShare,
                zoneID: scope.zoneID
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var fetched: CKShare?
            nonisolated(unsafe) var resultError: Error?
            scope.database.fetch(withRecordID: shareID) { record, error in
                if let error {
                    resultError = error
                }
                else {
                    fetched = record as? CKShare
                }
                sem.signal()
            }
            sem.wait()
            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(
                        error,
                        op: "Accepted share lookup"
                    )
                )
            }
            guard let fetched else {
                throw CloudKitError.NotFound(msg: "accepted CloudKit share")
            }
            return fetched
        }

    }

    // MARK: - Zones, record ids, and error classification

    extension CloudKitService {
        private func ensureZone() throws {
            guard !zoneEnsured else {
                return
            }
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?
            let zone = CKRecordZone(zoneID: privateZoneID)
            privateDatabase.save(zone) { _, error in
                resultError = error
                sem.signal()
            }
            sem.wait()
            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Zone setup")
                )
            }
            zoneEnsured = true
        }

        // MARK: - Record ID from key

        private struct RecordScope {
            let database: CKDatabase
            let zoneID: CKRecordZone.ID
            let ownsZone: Bool
        }

        private func recordScope(ownerName: String?, zoneName: String?) throws
            -> RecordScope
        {
            switch (ownerName, zoneName) {
            case (nil, nil):
                return RecordScope(
                    database: privateDatabase,
                    zoneID: privateZoneID,
                    ownsZone: true
                )
            case (.some(let ownerName), .some(let zoneName)):
                guard !ownerName.isEmpty, !zoneName.isEmpty else {
                    throw CloudKitError.Storage(
                        msg:
                            "CloudKit shared scope requires non-empty owner and zone names"
                    )
                }
                return RecordScope(
                    database: sharedDatabase,
                    zoneID: CKRecordZone.ID(
                        zoneName: zoneName,
                        ownerName: ownerName
                    ),
                    ownsZone: false
                )
            case (nil, .some(_)), (.some(_), nil):
                throw CloudKitError.Storage(
                    msg:
                        "CloudKit shared scope requires both owner and zone names"
                )
            }
        }

        private func recordID(for key: String, in scope: RecordScope)
            -> CKRecord.ID
        {
            CKRecord.ID(recordName: key, zoneID: scope.zoneID)
        }

        private func ensureWritableZone(for scope: RecordScope) throws {
            if scope.ownsZone {
                try ensureZone()
            }
        }

        // MARK: - Error classification

        /// Translate a CloudKit operation failure into a user-facing message that
        /// names the account/storage condition and the recovery step. The common
        /// `CKError` codes get specific copy; everything else falls back to the
        /// operation label + `localizedDescription` so transient or unclassified
        /// failures stay debuggable in logs.
        private func cloudKitErrorMessage(_ error: Error, op: String) -> String
        {
            guard let ckError = error as? CKError else {
                return "\(op) failed: \(error.displayLine)"
            }
            switch ckError.code {
            case .notAuthenticated:
                return
                    "You're not signed into iCloud. Open System Settings → Apple ID to sign in, then try again."
            case .quotaExceeded:
                return
                    "Your iCloud storage is full. Free up space in System Settings → Apple ID → iCloud to keep syncing."
            case .permissionFailure:
                return
                    "bae doesn't have permission to use iCloud. Open System Settings → Apple ID → iCloud → Apps Using iCloud and turn bae on."
            case .zoneNotFound, .userDeletedZone:
                return
                    "The iCloud sync zone is gone. Reconnect in sync settings to recreate it."
            default:
                return "\(op) failed: \(ckError.displayLine)"
            }
        }

    }

    // MARK: - Versioned reads and atomic record batches

    extension CloudKitService {
        /// Read a record and hand back CloudKit's own `recordChangeTag` with the
        /// bytes. coven names the exact version it read when it later deletes,
        /// so the tag has to come from the same fetch as the payload.
        public func readVersionedRecord(
            ownerName: String?,
            zoneName: String?,
            key: String
        ) throws -> BridgeCloudVersionedObject {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let record = try fetchRecord(key: key, in: scope)
            guard let asset = record["data"] as? CKAsset,
                let url = asset.fileURL
            else {
                throw CloudKitError.NotFound(msg: key)
            }
            guard let tag = record.recordChangeTag else {
                throw CloudKitError.Storage(
                    msg:
                        "CloudKit record \(key) has no change tag to version it by"
                )
            }
            do {
                return BridgeCloudVersionedObject(
                    bytes: try Data(contentsOf: url),
                    version: tag
                )
            }
            catch {
                throw CloudKitError.Storage(
                    msg: "Read failed: \(error.localizedDescription)"
                )
            }
        }

        /// Open a staging batch. Nothing reaches CloudKit until the commit: the
        /// payloads sit in host-owned temporary files so the whole set can be
        /// created in one atomic zone modification.
        public func beginAtomicCreate(ownerName: String?, zoneName: String?)
            throws -> String
        {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            try ensureWritableZone(for: scope)
            let batch = UUID().uuidString
            let directory = stagingDirectory(batch: batch)
            do {
                try FileManager.default.createDirectory(
                    at: directory,
                    withIntermediateDirectories: true
                )
            }
            catch {
                throw CloudKitError.Storage(
                    msg:
                        "CloudKit staging setup failed: \(error.localizedDescription)"
                )
            }
            stagingLock.lock()
            staged[batch] = []
            stagingLock.unlock()
            return batch
        }

        public func stageAtomicCreateRecord(
            ownerName: String?,
            zoneName: String?,
            batch: String,
            record: BridgeCloudKitRecordCreate
        ) throws {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let payloadURL = stagingDirectory(batch: batch)
                .appendingPathComponent(UUID().uuidString)
            do { try record.data.write(to: payloadURL) }
            catch {
                throw CloudKitError.Storage(
                    msg:
                        "CloudKit staging write failed: \(error.localizedDescription)"
                )
            }
            let ckRecord = CKRecord(
                recordType: recordType,
                recordID: recordID(for: record.key, in: scope)
            )
            ckRecord["key"] = record.key as CKRecordValue
            ckRecord["data"] = CKAsset(fileURL: payloadURL)

            stagingLock.lock()
            defer { stagingLock.unlock() }
            guard staged[batch] != nil else {
                throw CloudKitError.NotFound(
                    msg: "CloudKit staging batch \(batch)"
                )
            }
            staged[batch]?
                .append(StagedRecord(key: record.key, record: ckRecord))
        }

        /// Create every staged record in one atomic zone modification, create-only.
        ///
        /// `.ifServerRecordUnchanged` on a record with no change tag is CloudKit's
        /// create-only save: an existing record fails the save rather than being
        /// overwritten, and `isAtomic` makes one such failure fail the whole set,
        /// so a rejected batch leaves nothing behind. A lost response is a
        /// different case — the records may well be there, so nothing is cleaned
        /// up here; coven reads the keys back to settle it.
        public func commitAtomicCreate(
            ownerName: String?,
            zoneName: String?,
            batch: String
        ) throws -> [BridgeCloudKitRecordVersion] {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            stagingLock.lock()
            let records = staged[batch]
            stagingLock.unlock()
            guard let records else {
                throw CloudKitError.NotFound(
                    msg: "CloudKit staging batch \(batch)"
                )
            }

            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var savedByName: [String: CKRecord] = [:]
            nonisolated(unsafe) var resultError: Error?
            let op = CKModifyRecordsOperation(
                recordsToSave: records.map(\.record),
                recordIDsToDelete: nil
            )
            op.savePolicy = .ifServerRecordUnchanged
            op.isAtomic = true
            op.perRecordSaveBlock = { recordID, result in
                if case .success(let record) = result {
                    savedByName[recordID.recordName] = record
                }
            }
            op.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result { resultError = error }
                sem.signal()
            }
            scope.database.add(op)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Atomic create")
                )
            }
            // Staging order is the order coven expects its versions back in.
            return try records.map { staged in
                guard
                    let saved = savedByName[
                        recordID(for: staged.key, in: scope).recordName
                    ],
                    let tag = saved.recordChangeTag
                else {
                    throw CloudKitError.Storage(
                        msg:
                            "CloudKit did not return a change tag for created record \(staged.key)"
                    )
                }
                return BridgeCloudKitRecordVersion(
                    key: staged.key,
                    version: tag
                )
            }
        }

        /// Drop host-local staging. Never touches records the batch may already
        /// have created, and does nothing for a batch that is already gone.
        public func discardAtomicCreate(
            ownerName: String?,
            zoneName: String?,
            batch: String
        ) throws {
            stagingLock.lock()
            staged.removeValue(forKey: batch)
            stagingLock.unlock()
            let directory = stagingDirectory(batch: batch)
            guard FileManager.default.fileExists(atPath: directory.path) else {
                return
            }
            do { try FileManager.default.removeItem(at: directory) }
            catch {
                throw CloudKitError.Storage(
                    msg:
                        "CloudKit staging batch \(batch) could not be discarded: "
                        + error.localizedDescription
                )
            }
        }

        /// Delete exactly these versions, all or nothing.
        ///
        /// CloudKit has no per-delete change-tag precondition, so the versions
        /// are checked first: every record is fetched and its tag compared, and
        /// only then does the atomic zone modification run. A record that moved
        /// or vanished in between fails the whole deletion, which is what the
        /// caller relies on.
        public func deleteRecordVersions(
            ownerName: String?,
            zoneName: String?,
            records: [BridgeCloudKitRecordVersion]
        ) throws {
            guard !records.isEmpty else { return }
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            for record in records {
                let current = try fetchRecord(key: record.key, in: scope)
                guard current.recordChangeTag == record.version else {
                    throw CloudKitError.Storage(
                        msg:
                            "CloudKit record \(record.key) changed before its exact deletion"
                    )
                }
            }

            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?
            let op = CKModifyRecordsOperation(
                recordsToSave: nil,
                recordIDsToDelete: records.map {
                    recordID(for: $0.key, in: scope)
                }
            )
            op.isAtomic = true
            op.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result { resultError = error }
                sem.signal()
            }
            scope.database.add(op)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Exact delete")
                )
            }
        }

        private struct StagedRecord {
            let key: String
            let record: CKRecord
        }

        private func stagingDirectory(batch: String) -> URL {
            FileManager.default.temporaryDirectory
                .appendingPathComponent("bae-cloudkit-staging")
                .appendingPathComponent(batch)
        }

        private func fetchRecord(key: String, in scope: RecordScope) throws
            -> CKRecord
        {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var fetched: CKRecord?
            nonisolated(unsafe) var resultError: Error?
            scope.database.fetch(withRecordID: recordID(for: key, in: scope)) {
                record,
                error in
                if let error {
                    resultError = error
                }
                else {
                    fetched = record
                }
                sem.signal()
            }
            sem.wait()
            if let error = resultError {
                if let ckError = error as? CKError, ckError.code == .unknownItem
                {
                    throw CloudKitError.NotFound(msg: key)
                }
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Read")
                )
            }
            guard let fetched else { throw CloudKitError.NotFound(msg: key) }
            return fetched
        }
    }

    // MARK: - CloudKitDriver Protocol

    extension CloudKitService {
        public func writeRecord(
            ownerName: String?,
            zoneName: String?,
            key: String,
            data: Data
        ) throws {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            try ensureWritableZone(for: scope)
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?

            let tempURL = FileManager.default.temporaryDirectory
                .appendingPathComponent(UUID().uuidString)
            try data.write(to: tempURL)
            defer {
                do {
                    try FileManager.default.removeItem(at: tempURL)
                }
                catch {
                    logger.warning(
                        "failed to remove temp file \(tempURL.path): \(error.localizedDescription)"
                    )
                }
            }

            let record = CKRecord(
                recordType: recordType,
                recordID: recordID(for: key, in: scope)
            )
            record["key"] = key as CKRecordValue
            record["data"] = CKAsset(fileURL: tempURL)

            let op = CKModifyRecordsOperation(
                recordsToSave: [record],
                recordIDsToDelete: nil
            )
            op.savePolicy = .allKeys
            op.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            scope.database.add(op)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Write")
                )
            }
        }

        public func readRecord(
            ownerName: String?,
            zoneName: String?,
            key: String
        ) throws -> Data {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultData: Data?
            nonisolated(unsafe) var resultError: Error?

            scope.database.fetch(withRecordID: recordID(for: key, in: scope)) {
                record,
                error in
                if let error {
                    resultError = error
                }
                else if let record, let asset = record["data"] as? CKAsset,
                    let url = asset.fileURL
                {
                    do {
                        resultData = try Data(contentsOf: url)
                    }
                    catch {
                        resultError = error
                    }
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                if let ckError = error as? CKError, ckError.code == .unknownItem
                {
                    throw CloudKitError.NotFound(msg: key)
                }
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Read")
                )
            }
            guard let data = resultData else {
                throw CloudKitError.NotFound(msg: key)
            }
            return data
        }

        public func listRecords(
            ownerName: String?,
            zoneName: String?,
            prefix: String
        ) throws -> [String] {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            try ensureWritableZone(for: scope)
            var keys: [String] = []

            let predicate = NSPredicate(format: "key BEGINSWITH %@", prefix)
            let query = CKQuery(recordType: recordType, predicate: predicate)

            var cursor = try fetchKeysPage(into: &keys) { handler in
                scope.database.fetch(
                    withQuery: query,
                    inZoneWith: scope.zoneID,
                    completionHandler: handler
                )
            }
            while let activeCursor = cursor {
                cursor = try fetchKeysPage(into: &keys) { handler in
                    scope.database.fetch(
                        withCursor: activeCursor,
                        completionHandler: handler
                    )
                }
            }

            return keys
        }

        /// Run one CloudKit query page synchronously: `issue` starts the fetch
        /// with the given completion handler (the initial `withQuery` or a
        /// follow-up `withCursor`). Appends every matched record's `key` to
        /// `keys` and returns the next page's cursor (`nil` when the last page is
        /// reached). Throws on the page's failure result.
        private func fetchKeysPage(
            into keys: inout [String],
            issue: (
                @escaping (
                    Result<
                        (
                            matchResults: [(
                                CKRecord.ID, Result<CKRecord, Error>
                            )],
                            queryCursor: CKQueryOperation.Cursor?
                        ),
                        Error
                    >
                ) -> Void
            ) -> Void
        ) throws -> CKQueryOperation.Cursor? {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var pageKeys: [String] = []
            nonisolated(unsafe) var resultError: Error?
            nonisolated(unsafe) var nextCursor: CKQueryOperation.Cursor?

            issue { result in
                switch result {
                case .success((let matchResults, let queryCursor)):
                    nextCursor = queryCursor
                    for (_, recordResult) in matchResults {
                        if case .success(let record) = recordResult,
                            let key = record["key"] as? String
                        {
                            pageKeys.append(key)
                        }
                    }
                case .failure(let error):
                    resultError = error
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "List")
                )
            }
            keys.append(contentsOf: pageKeys)
            return nextCursor
        }

        public func deleteRecord(
            ownerName: String?,
            zoneName: String?,
            key: String
        ) throws {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var resultError: Error?

            let op = CKModifyRecordsOperation(
                recordsToSave: nil,
                recordIDsToDelete: [recordID(for: key, in: scope)],
            )
            op.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result {
                    if let ckError = error as? CKError,
                        ckError.code == .unknownItem
                    {
                        // Idempotent delete
                    }
                    else {
                        resultError = error
                    }
                }
                sem.signal()
            }
            scope.database.add(op)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Delete")
                )
            }
        }

        public func recordExists(
            ownerName: String?,
            zoneName: String?,
            key: String
        ) throws -> Bool {
            let scope = try recordScope(
                ownerName: ownerName,
                zoneName: zoneName
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var exists = false
            nonisolated(unsafe) var resultError: Error?

            scope.database.fetch(withRecordID: recordID(for: key, in: scope)) {
                record,
                error in
                if let error {
                    if let ckError = error as? CKError,
                        ckError.code == .unknownItem
                    {
                        exists = false
                    }
                    else {
                        resultError = error
                    }
                }
                else {
                    exists = record != nil
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Exists check")
                )
            }
            return exists
        }

        public func grantShare(memberPubkey: String) throws
            -> BridgeCloudKitShare
        {
            try ensureZoneSupportsSharing()
            let share =
                try fetchZoneWideShare()
                ?? CKShare(
                    recordZoneID: privateZoneID
                )

            // URL-accept: anyone holding the share URL can accept and gets
            // read/write. Apple binds the accepting participant's identity at
            // accept time, so no participant is pre-added and no member email
            // is captured here — the joiner supplies only its key.
            share.publicPermission = .readWrite

            let savedShare = try saveShare(share, op: "Grant share")
            guard let shareURL = savedShare.url?.absoluteString else {
                throw CloudKitError.Storage(
                    msg: "CloudKit did not return a URL for the saved share"
                )
            }
            return BridgeCloudKitShare(
                shareUrl: shareURL,
                ownerName: savedShare.recordID.zoneID.ownerName,
                zoneName: savedShare.recordID.zoneID.zoneName
            )
        }

        /// Revoking a member's content access rides on coven's library-key
        /// rotation, exactly like S3's `revoke_access`: the removed member may
        /// still read the CloudKit ciphertext but cannot decrypt anything
        /// written after the key rotates. A public URL-accept share carries no
        /// per-member participant mapping to remove, so this is a deliberate
        /// near-no-op. It does not throw, and does not claim to remove a
        /// participant it cannot identify. Precise per-participant CKShare
        /// removal is a follow-up that needs an identity binding written at
        /// accept time.
        public func revokeShare(memberPubkey: String) throws {
            // Nothing to remove on the share itself; access loss follows from
            // coven rotating the library key.
        }

        public func acceptShare(shareUrl: String) throws -> BridgeCloudKitShare
        {
            guard let url = URL(string: shareUrl) else {
                throw CloudKitError.Storage(
                    msg: "CloudKit share URL is invalid"
                )
            }
            let metadata = try fetchShareMetadata(url: url)
            let acceptedShare = try acceptShare(metadata: metadata)
            return BridgeCloudKitShare(
                shareUrl: shareUrl,
                ownerName: acceptedShare.recordID.zoneID.ownerName,
                zoneName: acceptedShare.recordID.zoneID.zoneName
            )
        }

        private func ensureZoneSupportsSharing() throws {
            try ensureZone()
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var fetchedZone: CKRecordZone?
            nonisolated(unsafe) var resultError: Error?

            privateDatabase.fetch(withRecordZoneID: privateZoneID) {
                zone,
                error in
                if let error {
                    resultError = error
                }
                else {
                    fetchedZone = zone
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Share zone lookup")
                )
            }
            guard let fetchedZone else {
                throw CloudKitError.Storage(
                    msg: "CloudKit sharing zone was not returned"
                )
            }
            guard fetchedZone.capabilities.contains(.zoneWideSharing) else {
                throw CloudKitError.Storage(
                    msg: "CloudKit zone-wide sharing is not available"
                )
            }
        }

        private func fetchZoneWideShare() throws -> CKShare? {
            let shareID = CKRecord.ID(
                recordName: CKRecordNameZoneWideShare,
                zoneID: privateZoneID
            )
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var share: CKShare?
            nonisolated(unsafe) var resultError: Error?

            privateDatabase.fetch(withRecordID: shareID) { record, error in
                if let error {
                    if let ckError = error as? CKError,
                        ckError.code == .unknownItem
                    {
                        share = nil
                    }
                    else {
                        resultError = error
                    }
                }
                else if let fetchedShare = record as? CKShare {
                    share = fetchedShare
                }
                else if record != nil {
                    resultError = CloudKitError.Storage(
                        msg:
                            "CloudKit zone-wide share record has an unexpected type"
                    )
                }
                sem.signal()
            }
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Share lookup")
                )
            }
            return share
        }

        private func saveShare(_ share: CKShare, op: String) throws -> CKShare {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var savedShare: CKShare?
            nonisolated(unsafe) var resultError: Error?

            let operation = CKModifyRecordsOperation(
                recordsToSave: [share],
                recordIDsToDelete: nil
            )
            operation.savePolicy = .allKeys
            operation.perRecordSaveBlock = { _, result in
                switch result {
                case .success(let record):
                    if let share = record as? CKShare {
                        savedShare = share
                    }
                    else {
                        resultError = CloudKitError.Storage(
                            msg: "\(op) returned a non-share record"
                        )
                    }
                case .failure(let error):
                    resultError = error
                }
            }
            operation.modifyRecordsResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            privateDatabase.add(operation)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: op)
                )
            }
            guard let savedShare else {
                throw CloudKitError.Storage(
                    msg: "\(op) failed: CloudKit did not return a share"
                )
            }
            return savedShare
        }

        private func fetchShareMetadata(url: URL) throws -> CKShare.Metadata {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var metadata: CKShare.Metadata?
            nonisolated(unsafe) var resultError: Error?

            let operation = CKFetchShareMetadataOperation(shareURLs: [url])
            operation.perShareMetadataResultBlock = { _, result in
                switch result {
                case .success(let fetchedMetadata):
                    metadata = fetchedMetadata
                case .failure(let error):
                    resultError = error
                }
            }
            operation.fetchShareMetadataResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            operation.container = container
            operation.qualityOfService = .userInitiated
            operation.start()
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(
                        error,
                        op: "Share metadata lookup"
                    )
                )
            }
            guard let metadata else {
                throw CloudKitError.Storage(
                    msg: "CloudKit did not return share metadata"
                )
            }
            return metadata
        }

        private func acceptShare(metadata: CKShare.Metadata) throws -> CKShare {
            let sem = DispatchSemaphore(value: 0)
            nonisolated(unsafe) var acceptedShare: CKShare?
            nonisolated(unsafe) var resultError: Error?

            let operation = CKAcceptSharesOperation(shareMetadatas: [metadata])
            operation.perShareResultBlock = { _, result in
                switch result {
                case .success(let share):
                    acceptedShare = share
                case .failure(let error):
                    resultError = error
                }
            }
            operation.acceptSharesResultBlock = { result in
                if case .failure(let error) = result {
                    resultError = error
                }
                sem.signal()
            }
            operation.qualityOfService = .userInitiated
            container.add(operation)
            sem.wait()

            if let error = resultError {
                throw CloudKitError.Storage(
                    msg: cloudKitErrorMessage(error, op: "Accept share")
                )
            }
            guard let acceptedShare else {
                throw CloudKitError.Storage(
                    msg: "CloudKit did not return accepted share"
                )
            }
            return acceptedShare
        }
    }

#endif
