//! The theme as Kotlin for Compose, and the launch window's colour resources.

use std::fmt::Write;

use crate::{Argb, Roles, Theme};

/// The Kotlin file, named relative to the output directory.
pub const KOTLIN_FILE: &str = "kotlin/fm/bae/app/ui/appearance/ThemePalette.kt";

/// The launch window's background before Compose draws, as resource files
/// named relative to the output directory: the first tone in each appearance.
pub fn launch_resources(theme: &Theme) -> Result<Vec<(String, String)>, String> {
    let tone = &theme.tones[0];
    [("values", &tone.surfaces.light), ("values-night", &tone.surfaces.dark)]
        .into_iter()
        .map(|(qualifier, surfaces)| {
            let background = surfaces
                .get("background")
                .ok_or_else(|| format!("tone {} has no `background` for the launch window", tone.name))?;
            Ok((
                format!("res/{qualifier}/theme_colors.xml"),
                format!(
                    "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
                     <!-- Generated by theme-gen from design/theme.toml; edit that file instead. -->\n\
                     <resources>\n    <color name=\"appearance_launch_background\">#{:08X}</color>\n</resources>\n",
                    background.0
                ),
            ))
        })
        .collect()
}

pub fn kotlin(theme: &Theme) -> String {
    let mut out = String::from(
        "// Generated by theme-gen from design/theme.toml; edit that file instead.\n\n\
         package fm.bae.app.ui.appearance\n\n\
         import androidx.compose.ui.graphics.Color\n\
         import androidx.compose.ui.unit.dp\n",
    );
    choice_enum(
        &mut out,
        "SurfaceTone",
        theme.tones.iter().map(|tone| tone.name.as_str()),
    );
    choice_enum(
        &mut out,
        "AccentChoice",
        theme.accents.iter().map(|accent| accent.name.as_str()),
    );

    roles_class(
        &mut out,
        "One tone's surfaces in one appearance.",
        "ToneSurfaces",
        &theme.tones[0].surfaces.light,
    );
    out.push_str(
        "\n/** One accent's colours: text and glyphs in each appearance, and the fill behind white button labels. */\n\
         class AccentColors(\n    val dark: Color,\n    val fill: Color,\n    val light: Color,\n)\n",
    );
    roles_class(
        &mut out,
        "Colours that mean the same in every tone, in one appearance.",
        "SemanticColors",
        &theme.semantics.light,
    );

    out.push_str("\nfun SurfaceTone.surfaces(dark: Boolean): ToneSurfaces =\n    when (this) {\n");
    for tone in &theme.tones {
        let _ = writeln!(out, "        SurfaceTone.{} ->", tone.name.to_uppercase());
        let _ = writeln!(out, "            if (dark) {{");
        roles_value(&mut out, "ToneSurfaces", &tone.surfaces.dark, 16);
        let _ = writeln!(out, "            }} else {{");
        roles_value(&mut out, "ToneSurfaces", &tone.surfaces.light, 16);
        let _ = writeln!(out, "            }}");
    }
    out.push_str("    }\n");

    out.push_str("\nval AccentChoice.colors: AccentColors\n    get() =\n        when (this) {\n");
    for accent in &theme.accents {
        let _ = writeln!(
            out,
            "            AccentChoice.{} ->",
            accent.name.to_uppercase()
        );
        let roles: Roles = [
            ("light", accent.light),
            ("dark", accent.dark),
            ("fill", accent.fill),
        ]
        .into_iter()
        .map(|(name, colour)| (name.to_string(), colour))
        .collect();
        roles_value(&mut out, "AccentColors", &roles, 16);
    }
    out.push_str("        }\n");

    out.push_str("\nfun semanticColors(dark: Boolean): SemanticColors =\n    if (dark) {\n");
    roles_value(&mut out, "SemanticColors", &theme.semantics.dark, 8);
    out.push_str("    } else {\n");
    roles_value(&mut out, "SemanticColors", &theme.semantics.light, 8);
    out.push_str("    }\n");

    out.push_str(
        "\n/** How opaque a colour is laid over what is behind it. */\nobject ThemeOpacity {\n",
    );
    for (role, value) in &theme.opacity {
        let _ = writeln!(out, "    const val {role}: Float = {value:?}f");
    }
    out.push_str("}\n");

    out.push_str("\n/** Corner radii. */\nobject ThemeRadius {\n");
    for (role, value) in &theme.radius {
        let _ = writeln!(out, "    val {role} = {value}.dp");
    }
    out.push_str("}\n");
    out
}

fn choice_enum<'a>(out: &mut String, name: &str, entries: impl Iterator<Item = &'a str>) {
    let _ = writeln!(out, "\nenum class {name} {{");
    for entry in entries {
        let _ = writeln!(out, "    {},", entry.to_uppercase());
    }
    out.push_str("}\n");
}

fn roles_class(out: &mut String, doc: &str, name: &str, roles: &Roles) {
    let _ = writeln!(out, "\n/** {doc} */\nclass {name}(");
    for role in roles.keys() {
        let _ = writeln!(out, "    val {role}: Color,");
    }
    out.push_str(")\n");
}

/// A constructor call with one named colour argument per role, one per line.
fn roles_value(out: &mut String, name: &str, roles: &Roles, indent: usize) {
    let pad = " ".repeat(indent);
    let _ = writeln!(out, "{pad}{name}(");
    for (role, colour) in roles {
        let _ = writeln!(out, "{pad}    {role} = {},", color(*colour));
    }
    let _ = writeln!(out, "{pad})");
}

fn color(colour: Argb) -> String {
    format!("Color(0x{:08X})", colour.0)
}
