//! The theme as Swift for BaeKit.

use std::fmt::Write;

use crate::{Argb, Roles, Theme};

/// The file BaeKit compiles, named relative to its output directory.
pub const FILE: &str = "ThemePalette.swift";

pub fn swift(theme: &Theme) -> String {
    let mut out = String::from(
        "// Generated by theme-gen from design/theme.toml; edit that file instead.\n\n\
         import SwiftUI\n",
    );
    choice_enum(
        &mut out,
        "SurfaceTone",
        theme.tones.iter().map(|tone| tone.name.as_str()),
    );
    choice_enum(
        &mut out,
        "AccentChoice",
        theme.accents.iter().map(|accent| accent.name.as_str()),
    );

    out.push_str("\n/// One tone's surfaces in one appearance.\nstruct ToneSurfaces: Sendable {\n");
    for role in theme.tones[0].surfaces.light.keys() {
        let _ = writeln!(out, "    let {role}: Color");
    }
    out.push_str(
        "}\n\n/// One accent's colours: text and glyphs in each appearance, and the\n\
         /// fill behind white button labels.\n\
         struct AccentColors: Sendable {\n    let dark: Color\n    let fill: Color\n    let light: Color\n}\n",
    );

    out.push_str(
        "\nextension SurfaceTone {\n    func surfaces(dark: Bool) -> ToneSurfaces {\n        switch (self, dark) {\n",
    );
    for tone in &theme.tones {
        for (dark, roles) in [(false, &tone.surfaces.light), (true, &tone.surfaces.dark)] {
            let _ = writeln!(out, "        case (.{}, {dark}):", tone.name);
            roles_value(&mut out, "ToneSurfaces", roles, 12);
        }
    }
    out.push_str("        }\n    }\n}\n");

    out.push_str(
        "\nextension AccentChoice {\n    var colors: AccentColors {\n        switch self {\n",
    );
    for accent in &theme.accents {
        let _ = writeln!(out, "        case .{}:", accent.name);
        let roles: Roles = [
            ("light", accent.light),
            ("dark", accent.dark),
            ("fill", accent.fill),
        ]
        .into_iter()
        .map(|(name, colour)| (name.to_string(), colour))
        .collect();
        roles_value(&mut out, "AccentColors", &roles, 12);
    }
    out.push_str("        }\n    }\n}\n");

    out.push_str(
        "\n/// Colours that mean the same in every tone, each following the\n\
         /// appearance it is drawn in.\nextension Theme {\n",
    );
    for (role, light) in &theme.semantics.light {
        let dark = theme.semantics.dark[role];
        let _ = writeln!(
            out,
            "    public static let {role} = Color(\n        light: {},\n        dark: {}\n    )",
            hex(*light),
            hex(dark)
        );
    }
    out.push_str("}\n");

    out.push_str(
        "\n/// How opaque a colour is laid over what is behind it.\npublic enum ThemeOpacity {\n",
    );
    for (role, value) in &theme.opacity {
        let _ = writeln!(out, "    public static let {role}: Double = {value:?}");
    }
    out.push_str("}\n");

    out.push_str("\n/// Corner radii.\npublic enum ThemeRadius {\n");
    for (role, value) in &theme.radius {
        let _ = writeln!(out, "    public static let {role}: CGFloat = {value}");
    }
    out.push_str("}\n");

    out.push_str(
        "\n/// A text style: its font, letter spacing and case, and the size, style,\n\
         /// weight and design AppKit and UIKit text draw it with.\npublic struct ThemeText: Sendable {\n    \
         public let font: Font\n    public let tracking: CGFloat\n    public let uppercase: Bool\n    \
         public let macOSSize: CGFloat\n    public let iOSStyle: Font.TextStyle\n    public let weight: Font.Weight\n    \
         public let monospaced: Bool\n}\n\n\
         extension ThemeText {\n",
    );
    for (role, text) in &theme.text {
        let design = if text.monospaced {
            ".monospaced"
        } else {
            ".default"
        };
        let _ = writeln!(
            out,
            "    public static let {role} = ThemeText(\n        font: .theme(\n            macOS: {},\n            \
             iOS: .{},\n            weight: {},\n            design: {design}\n        ),\n        \
             tracking: {},\n        uppercase: {},\n        macOSSize: {},\n        iOSStyle: .{},\n        weight: {},\n        \
             monospaced: {}\n    )",
            text.macos,
            text.ios,
            text.weight.swift(),
            text.tracking,
            text.uppercase,
            text.macos,
            text.ios,
            text.weight.swift(),
            text.monospaced
        );
    }
    out.push_str("}\n");
    out.push_str(FONT_INITIALIZER);

    out.push_str("\n/// Gaps and insets.\npublic enum ThemeSpace {\n");
    for (role, value) in &theme.space {
        let _ = writeln!(out, "    public static let {role}: CGFloat = {value}");
    }
    out.push_str(
        "}\n\n/// A glyph's size and the weight it is drawn at.\npublic struct ThemeIcon: Sendable {\n    \
         public let size: CGFloat\n    public let weight: Font.Weight\n\n    \
         public var font: Font {\n        .system(size: size, weight: weight)\n    }\n}\n\n\
         extension ThemeIcon {\n",
    );
    for (role, icon) in &theme.icon {
        let _ = writeln!(
            out,
            "    public static let {role} = ThemeIcon(\n        size: .platform(macOS: {}, iOS: {}),\n        \
             weight: {}\n    )",
            icon.sizes.macos,
            icon.sizes.ios,
            icon.weight.swift()
        );
    }
    out.push_str("}\n\n/// Sizes that recur across screens.\npublic enum ThemeSize {\n");
    for (role, lengths) in &theme.size {
        let _ = writeln!(
            out,
            "    public static let {role}: CGFloat = .platform(\n        macOS: {},\n        iOS: {}\n    )",
            lengths.macos, lengths.ios
        );
    }
    out.push_str("}\n");
    out.push_str(PLATFORM_LENGTH);

    out.push_str(COLOR_INITIALIZERS);
    out
}

/// A role's font: a point size on macOS, a Dynamic Type style on iOS.
const FONT_INITIALIZER: &str = "
extension Font {
    fileprivate static func theme(
        macOS size: CGFloat,
        iOS style: Font.TextStyle,
        weight: Font.Weight,
        design: Font.Design
    ) -> Font {
        #if os(macOS)
            .system(size: size, weight: weight, design: design)
        #else
            .system(style, design: design, weight: weight)
        #endif
    }
}
";

/// A length that differs between macOS and iOS.
const PLATFORM_LENGTH: &str = "
extension CGFloat {
    fileprivate static func platform(macOS: CGFloat, iOS: CGFloat) -> CGFloat {
        #if os(macOS)
            macOS
        #else
            iOS
        #endif
    }
}
";

/// Builds each colour from its bytes, and a semantic colour from its light
/// and dark values through the platform's appearance-aware colour.
const COLOR_INITIALIZERS: &str = "
extension Color {
    fileprivate init(argb: UInt32) {
        self.init(
            .sRGB,
            red: Double((argb >> 16) & 0xFF) / 255,
            green: Double((argb >> 8) & 0xFF) / 255,
            blue: Double(argb & 0xFF) / 255,
            opacity: Double(argb >> 24) / 255
        )
    }

    fileprivate init(light: UInt32, dark: UInt32) {
        #if canImport(AppKit)
            self.init(
                nsColor: NSColor(name: nil) { appearance in
                    let isDark =
                        appearance.bestMatch(from: [.aqua, .darkAqua])
                        == .darkAqua
                    return NSColor(Color(argb: isDark ? dark : light))
                }
            )
        #else
            self.init(
                uiColor: UIColor { traits in
                    UIColor(
                        Color(
                            argb: traits.userInterfaceStyle == .dark
                                ? dark : light
                        )
                    )
                }
            )
        #endif
    }
}
";

fn choice_enum<'a>(out: &mut String, name: &str, cases: impl Iterator<Item = &'a str>) {
    let _ = writeln!(
        out,
        "\npublic enum {name}: String, CaseIterable, Sendable {{"
    );
    for case in cases {
        let _ = writeln!(out, "    case {case}");
    }
    out.push_str("}\n");
}

/// An initializer call with one colour argument per role, one per line.
fn roles_value(out: &mut String, name: &str, roles: &Roles, indent: usize) {
    let pad = " ".repeat(indent);
    let _ = writeln!(out, "{pad}{name}(");
    let last = roles.len() - 1;
    for (index, (role, colour)) in roles.iter().enumerate() {
        let comma = if index == last { "" } else { "," };
        let _ = writeln!(out, "{pad}    {role}: Color(argb: {}){comma}", hex(*colour));
    }
    let _ = writeln!(out, "{pad})");
}

/// The colour's bytes as a Swift literal, grouped by four digits.
fn hex(colour: Argb) -> String {
    format!("0x{:04X}_{:04X}", colour.0 >> 16, colour.0 & 0xFFFF)
}
