//! The theme as Swift for BaeKit.

use std::fmt::Write;

use crate::{Argb, Roles, Theme};

/// The file BaeKit compiles, named relative to its output directory.
pub const FILE: &str = "ThemePalette.swift";

pub fn swift(theme: &Theme) -> String {
    let mut out = String::from(
        "// Generated by theme-gen from design/theme.toml; edit that file instead.\n\n\
         import SwiftUI\n",
    );
    choice_enum(
        &mut out,
        "SurfaceTone",
        theme.tones.iter().map(|tone| tone.name.as_str()),
    );
    choice_enum(
        &mut out,
        "AccentChoice",
        theme.accents.iter().map(|accent| accent.name.as_str()),
    );

    let surfaces = &theme.tones[0].surfaces.light;
    roles_struct(
        &mut out,
        "One tone's surfaces in one appearance.",
        "ToneSurfaces",
        surfaces,
    );
    out.push_str(
        "\n/// One accent's colours: text and glyphs in each appearance, and the\n\
         /// fill behind white button labels.\n\
         struct AccentColors: Sendable {\n    let dark: Color\n    let fill: Color\n    let light: Color\n}\n",
    );
    roles_struct(
        &mut out,
        "Colours that mean the same in every tone, in one appearance.",
        "SemanticColors",
        &theme.semantics.light,
    );

    out.push_str(
        "\nextension SurfaceTone {\n    func surfaces(dark: Bool) -> ToneSurfaces {\n        switch (self, dark) {\n",
    );
    for tone in &theme.tones {
        for (dark, roles) in [(false, &tone.surfaces.light), (true, &tone.surfaces.dark)] {
            let _ = writeln!(out, "        case (.{}, {dark}):", tone.name);
            roles_value(&mut out, "ToneSurfaces", roles, 12);
        }
    }
    out.push_str("        }\n    }\n}\n");

    out.push_str(
        "\nextension AccentChoice {\n    var colors: AccentColors {\n        switch self {\n",
    );
    for accent in &theme.accents {
        let _ = writeln!(out, "        case .{}:", accent.name);
        let roles: Roles = [
            ("light", accent.light),
            ("dark", accent.dark),
            ("fill", accent.fill),
        ]
        .into_iter()
        .map(|(name, colour)| (name.to_string(), colour))
        .collect();
        roles_value(&mut out, "AccentColors", &roles, 12);
    }
    out.push_str("        }\n    }\n}\n");

    out.push_str(
        "\nextension SemanticColors {\n    static func of(dark: Bool) -> SemanticColors {\n        switch dark {\n",
    );
    for (dark, roles) in [
        (false, &theme.semantics.light),
        (true, &theme.semantics.dark),
    ] {
        let _ = writeln!(out, "        case {dark}:");
        roles_value(&mut out, "SemanticColors", roles, 12);
    }
    out.push_str("        }\n    }\n}\n");

    out.push_str(
        "\nextension Color {\n\
         \x20   fileprivate init(argb: UInt32) {\n\
         \x20       self.init(\n\
         \x20           .sRGB,\n\
         \x20           red: Double((argb >> 16) & 0xFF) / 255,\n\
         \x20           green: Double((argb >> 8) & 0xFF) / 255,\n\
         \x20           blue: Double(argb & 0xFF) / 255,\n\
         \x20           opacity: Double(argb >> 24) / 255\n\
         \x20       )\n\
         \x20   }\n\
         }\n",
    );
    out
}

fn choice_enum<'a>(out: &mut String, name: &str, cases: impl Iterator<Item = &'a str>) {
    let _ = writeln!(
        out,
        "\npublic enum {name}: String, CaseIterable, Sendable {{"
    );
    for case in cases {
        let _ = writeln!(out, "    case {case}");
    }
    out.push_str("}\n");
}

fn roles_struct(out: &mut String, doc: &str, name: &str, roles: &Roles) {
    let _ = writeln!(out, "\n/// {doc}\nstruct {name}: Sendable {{");
    for role in roles.keys() {
        let _ = writeln!(out, "    let {role}: Color");
    }
    out.push_str("}\n");
}

/// An initializer call with one colour argument per role, one per line.
fn roles_value(out: &mut String, name: &str, roles: &Roles, indent: usize) {
    let pad = " ".repeat(indent);
    let _ = writeln!(out, "{pad}{name}(");
    let last = roles.len() - 1;
    for (index, (role, colour)) in roles.iter().enumerate() {
        let comma = if index == last { "" } else { "," };
        let _ = writeln!(out, "{pad}    {role}: {}{comma}", color(*colour));
    }
    let _ = writeln!(out, "{pad})");
}

fn color(colour: Argb) -> String {
    format!(
        "Color(argb: 0x{:04X}_{:04X})",
        colour.0 >> 16,
        colour.0 & 0xFFFF
    )
}
