-- The `imports` table recorded a status per import (`importing` → `complete` /
-- `failed`) that nothing ever read back: no production caller selected from it, and
-- it is device-local, so no peer saw it either. It also went stale — cancelling a
-- release's upload left its row `importing` forever, since the cancel has no reason
-- to touch a table nobody reads.
--
-- The two facts it was standing in for are owned elsewhere, correctly: an import
-- still uploading is coven's `cloud_outbox` (which a cancel clears, and which the
-- Processing pane renders), and an import in progress is the import service's
-- in-memory snapshot. Nothing here is recoverable from a status column, so the
-- column goes rather than gaining a reader.
DROP TABLE IF EXISTS imports;
