package fm.bae.app.ui

import android.app.Activity
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.SideEffect
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalView
import androidx.core.view.WindowCompat

// Material Design 3 color scheme generated by Material Theme Builder.
// Light scheme
private val BaeLightPrimary = Color(0xFFB8543A)
private val BaeLightOnPrimary = Color(0xFFFFFFFF)
private val BaeLightPrimaryContainer = Color(0xFFFFDAD0)
private val BaeLightOnPrimaryContainer = Color(0xFF3B0900)
private val BaeLightSecondary = Color(0xFF386A6A)
private val BaeLightOnSecondary = Color(0xFFFFFFFF)
private val BaeLightSecondaryContainer = Color(0xFFBCECEB)
private val BaeLightOnSecondaryContainer = Color(0xFF002020)
private val BaeLightTertiary = Color(0xFF4E5F88)
private val BaeLightOnTertiary = Color(0xFFFFFFFF)
private val BaeLightTertiaryContainer = Color(0xFFD9E2FF)
private val BaeLightOnTertiaryContainer = Color(0xFF071A42)
private val BaeLightBackground = Color(0xFFFCFCFF)
private val BaeLightOnBackground = Color(0xFF1A1C1E)
private val BaeLightSurface = Color(0xFFFCFCFF)
private val BaeLightOnSurface = Color(0xFF1A1C1E)
private val BaeLightSurfaceVariant = Color(0xFFDDE5E8)
private val BaeLightOnSurfaceVariant = Color(0xFF41484C)
private val BaeLightError = Color(0xFFBA1A1A)
private val BaeLightOnError = Color(0xFFFFFFFF)
private val BaeLightErrorContainer = Color(0xFFFFDAD6)
private val BaeLightOnErrorContainer = Color(0xFF410002)

// Dark scheme
private val BaeDarkPrimary = Color(0xFFFFB5A0)
private val BaeDarkOnPrimary = Color(0xFF5F1708)
private val BaeDarkPrimaryContainer = Color(0xFF833020)
private val BaeDarkOnPrimaryContainer = Color(0xFFFFDAD0)
private val BaeDarkSecondary = Color(0xFFA0CFCE)
private val BaeDarkOnSecondary = Color(0xFF003737)
private val BaeDarkSecondaryContainer = Color(0xFF1E4E4E)
private val BaeDarkOnSecondaryContainer = Color(0xFFBCECEB)
private val BaeDarkTertiary = Color(0xFFB7C7F7)
private val BaeDarkOnTertiary = Color(0xFF1F2F57)
private val BaeDarkTertiaryContainer = Color(0xFF36466F)
private val BaeDarkOnTertiaryContainer = Color(0xFFD9E2FF)
private val BaeDarkBackground = Color(0xFF0F1117)
private val BaeDarkOnBackground = Color(0xFFE4E8ED)
private val BaeDarkSurface = Color(0xFF171922)
private val BaeDarkOnSurface = Color(0xFFE4E8ED)
private val BaeDarkSurfaceVariant = Color(0xFF40484C)
private val BaeDarkOnSurfaceVariant = Color(0xFFC0C8CC)
private val BaeDarkError = Color(0xFFFFB4AB)
private val BaeDarkOnError = Color(0xFF690005)
private val BaeDarkErrorContainer = Color(0xFF93000A)
private val BaeDarkOnErrorContainer = Color(0xFFFFDAD6)

private val baeLightColorScheme =
    lightColorScheme(
        primary = BaeLightPrimary,
        onPrimary = BaeLightOnPrimary,
        primaryContainer = BaeLightPrimaryContainer,
        onPrimaryContainer = BaeLightOnPrimaryContainer,
        secondary = BaeLightSecondary,
        onSecondary = BaeLightOnSecondary,
        secondaryContainer = BaeLightSecondaryContainer,
        onSecondaryContainer = BaeLightOnSecondaryContainer,
        tertiary = BaeLightTertiary,
        onTertiary = BaeLightOnTertiary,
        tertiaryContainer = BaeLightTertiaryContainer,
        onTertiaryContainer = BaeLightOnTertiaryContainer,
        background = BaeLightBackground,
        onBackground = BaeLightOnBackground,
        surface = BaeLightSurface,
        onSurface = BaeLightOnSurface,
        surfaceVariant = BaeLightSurfaceVariant,
        onSurfaceVariant = BaeLightOnSurfaceVariant,
        error = BaeLightError,
        onError = BaeLightOnError,
        errorContainer = BaeLightErrorContainer,
        onErrorContainer = BaeLightOnErrorContainer,
    )

private val baeDarkColorScheme =
    darkColorScheme(
        primary = BaeDarkPrimary,
        onPrimary = BaeDarkOnPrimary,
        primaryContainer = BaeDarkPrimaryContainer,
        onPrimaryContainer = BaeDarkOnPrimaryContainer,
        secondary = BaeDarkSecondary,
        onSecondary = BaeDarkOnSecondary,
        secondaryContainer = BaeDarkSecondaryContainer,
        onSecondaryContainer = BaeDarkOnSecondaryContainer,
        tertiary = BaeDarkTertiary,
        onTertiary = BaeDarkOnTertiary,
        tertiaryContainer = BaeDarkTertiaryContainer,
        onTertiaryContainer = BaeDarkOnTertiaryContainer,
        background = BaeDarkBackground,
        onBackground = BaeDarkOnBackground,
        surface = BaeDarkSurface,
        onSurface = BaeDarkOnSurface,
        surfaceVariant = BaeDarkSurfaceVariant,
        onSurfaceVariant = BaeDarkOnSurfaceVariant,
        error = BaeDarkError,
        onError = BaeDarkOnError,
        errorContainer = BaeDarkErrorContainer,
        onErrorContainer = BaeDarkOnErrorContainer,
    )

@Composable
fun BaeTheme(content: @Composable () -> Unit) {
    val isDark = isSystemInDarkTheme()
    val colorScheme = if (isDark) baeDarkColorScheme else baeLightColorScheme
    val view = LocalView.current
    if (!view.isInEditMode) {
        val activity = view.context as Activity
        SideEffect {
            val window = activity.window
            val barsAreLight = !isDark
            val insetsController = WindowCompat.getInsetsController(window, view)
            insetsController.isAppearanceLightStatusBars = barsAreLight
            insetsController.isAppearanceLightNavigationBars = barsAreLight
        }
    }
    MaterialTheme(
        colorScheme = colorScheme,
        content = content,
    )
}
